### ISSUE TITLE
add setup instructions to README

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#1]
When I copied the code from https://github.com/IQSS/miniverse I did not include all the `python manage.py` and related Django commands from the README. These should be tested and added.

**Comment by pdurbin** [comment]
I don't want to say this is done but I did add a quickstart to the readme the other day: https://github.com/IQSS/dataverse-installations#quickstart

**Comment by pdurbin** [comment]
Everything changed in this repo recently when I switched the architecture from database/Django to a pure client side application pulling data from a JSON file.

Yesterday @donsizemore made a pull request to update information in the map.

I still need to document in the README what data comes from which Google spreadsheet or which external JSON file.

And I need to document how to run the Python script to update data.json.

If someone wants to help with this, please get in touch! :smile:

**Comment by pdurbin** [comment]
In 721deae I just started a list of where the data comes from.

**Comment by pdurbin** [comment]
@shlake thank you SO MUCH for letting me do a big brain dump just now about dataverse-installations! As we discussed, I just created a column for you on my board and moved this issue to the very top: https://github.com/orgs/IQSS/projects/3#column-6923468

Also as we discussed, you are now a member of @IQSS/dataverse-installations-admin 

![Screen Shot 2019-10-25 at 11 26 59 AM](https://user-images.githubusercontent.com/21006/67583874-770c0e80-f71a-11e9-9a5f-abd07886634b.png)

This means that you can push to master, as we did this morning, and that you can merge pull requests. So if @philippconzett follow up on pull request #13 with another pull request and it looks good, please go ahead and merge it! 😄 

As you work on the README, please commit directly to master rather than bothering with pull requests. Once we're happy enough with it, we'll close this issue and open new issues in the future. I'm thinking the scope for this issue is the following:

- Document each field in data.json and its source of truth using the existing table.
- Explain that Python 3 is required and how to run the script.

Once we have those two things in place, it should be much easier for others to contribute. Thanks! 🎉

**Comment by pdurbin** [comment]
> Explain that Python 3 is required and how to run the script.

I just left a brain dump about this at https://github.com/IQSS/dataverse-installations/pull/25#issuecomment-548754381

**Comment by shlake** [comment]
Will work on README tomorrow (11/8). I've been thinking about all the info that needs to go on the README and that it might be better to have a short "how to install" on README and put details as to "sources of truth" and other "tricks" in the wiki (and of course link the wiki from the README). 

So I have been "organizing" my thoughts.

**Comment by pdurbin** [comment]
@shlake sure! I'm not it the habit of using the wiki built into GitHub but plenty of projects do! Sounds good! Thanks!
