### ISSUE TITLE
Add my Dataverse repository: George Mason University Dataverse

### ISSUE THREAD

**Issue by wendysmann** [IQSS/dataverse-installations#100]
**Name of repository:**
George Mason University Dataverse

**Homepage URL of repository:**
https://dataverse.orc.gmu.edu

**Location of the repository (city or street address if possible):**
4400 University Dr. Fairfax, VA 22030

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
George Mason University Libraries Dataverse publishes, shares, and preserves data of enduring value produced by George Mason faculty, staff, and students.

**Email address of repository contact:**
datahelp@gmu.edu

**Year when repository started operating:**
2021

**DOI authority (if applicable):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by shlake** [comment]
@wendysmann YAY!!! George Mason is now on the map!!
https://iqss.github.io/dataverse-installations/

**Comment by wendysmann** [comment]
Wow that was fast. Thank you!!
