### ISSUE TITLE
Italian Institute of Technology (IIT) Dataverse Installation

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse-installations#102]
**Name of repository:**

IIT Dataverse

**Homepage URL of repository:**

https://dataverse.iit.it/

**Location of the repository (city or street address if possible):**

Via Morego, 30 16163 Genova

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**

IIT Dataverse is the research data repository of Istituto Italiano di Tecnologia and has been launched in May 2021. IIT’s research activity is focused on cutting-edge science in four Research Domains (Computational Sciences, LifeTech, Nanomaterials, and Robotics) and promotes excellence in basic and applied research. IIT Dataverse offers long-term storage and preservation to research data of IIT-affiliated researchers. IIT is also member of the Global Dataverse Community Consortium

**Email address of repository contact:**

Valentina.Pasquale@iit.it

**Year when repository started operating:**

2021

**DOI authority (if applicable):**

doi:10.48557

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by shlake** [comment]
Added to crowd-source spreadsheet.

Will run the update in a few....
