### ISSUE TITLE
Add my Dataverse repository: Lietuvos HSM duomenų archyvas (LiDA)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#104]
**Name of repository:**
Lietuvos HSM duomenų archyvas (LiDA)

**Homepage URL of repository:**
https://lida.dataverse.lt

**Location of the repository (city or street address if possible):**
K. Donelaičio g. 73, Kaunas 44249, Lithuania

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
Lietuvos HSM duomenų archyvas (LiDA) yra virtuali skaitmeninė empirinių HSM duomenų kaupimo, ilgalaikio saugojimo ir sklaidos infrastruktūra, suteikianti prieigą prie daugiau nei 700 duomenų rinkinių. LiDA Lietuvos socialinių mokslų bendruomenei užtikrina prieigą prie tarptautinių ir nacionalinių duomenų išteklių lietuvių ir anglų kalbomis. Prieigai prie duomenų rinkinių naudojama ši Dataverse talpykla (kol kas ne visi duomenų rinkiniai prieinami, nes 2019-2021 m. vykdomas perkėlimo iš senos infrastruktūros projektas). LiDA saugomi daugelio svarbiausių mokslinių tarptautinių tyrimų vykdomų Lietuvoje – Europos socialinio tyrimo, Europos vertybių studijos, Europos rinkimų studijos ir Tarptautinės socialinio tyrimo programos – duomenys.

LiDA kuruoja Kauno technologijos universiteto Duomenų analizės ir archyvavimo centras (data.ktu.edu)

**Email address of repository contact:**

**Year when repository started operating:**
2021

**DOI authority (if applicable):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by shlake** [comment]
@jggautier are you still having python problems adding to the map?

If so, I can do this later today.

**Comment by jggautier** [comment]
Hi @shlake. I think the problem I was having might've been resolved. 🤞 I'd like to try adding this one to the map (after the repository contact confirms the details).

**Comment by vaidasmo** [comment]
Hello,

We would like to add English description, as it seems to be more appropriate:

**Name of repository**:
Lithuanian Data Archive for Social Sciences and Humanities (LiDA)

**Homepage URL of repository**:
https://lida.dataverse.lt

**Location of the repository**:
A. Mickevičiaus g. 37-1100, LT-44244 Kaunas, Lithuania

The following isn't required but is nice to have:

**A short description (few sentences) about the repository**:
Lithuanian Data Archive for Social Sciences and Humanities (LiDA) is a virtual digital infrastructure for data acquisition, long-term preservation and dissemination. It provides access to more than 700 datasets. All the international and national data resources are documented in both Lithuanian and English. Access to the data is provided via this Dataverse repository (not all the datasets are available, as in 2019-2021 a migration project from the old infrastructure is being implemented). LiDA curates most of the data collected conducting the most important international social surveys in Lithuania – the European Social Survey, European Values Studies, European Election Studies and the International Social Research Program.
LiDA is hosted by the Centre for Data Analysis and Archiving of Kaunas University of Technology (data.ktu.edu). 

**Email address of repository contact**:
data@ktu.lt

**Year when repository started operating**:
2021

**Handle authority**:
EUDAT B2HANDLE (https://eudat.eu/services/userdoc/b2handle)

Link to successful Core Trust Seal application:
Not yet.

Thank you and best wishes,
Vaidas

**Comment by jggautier** [comment]
@shlake, I added the info to [the spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo) (row 43) but I'm still having a problem with the update-data.py script. Could you update the map when you get the chance?

(`response = urlrequest.urlopen(metrics_url)` on line 14 is still causing some sort of security error.)
