### ISSUE TITLE
Add my Dataverse repository: CORA. Research Data Repository (RDR)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#107]
**Name of repository:**
CORA. Research Data Repository (RDR)

**Homepage URL of repository:**
https://dataverse.csuc.cat

**Location of the repository (city or street address if possible):**
Consorci de Serveis Universitaris de Catalunya, Catalonia, Spain
41.38745981861992, 2.1120773040029754 ([Link to location on Google Maps](https://goo.gl/maps/Gr7MLJ17EXUUKB7M6))

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
CORA. Research Data Repository (RDR) is a federated and multidisciplinary data repository that allows Catalan universities, CERCA research centers and other entities that carry out research to publish research datasets in FAIR mode and following the EOSC guidelines. The objectives of the RDR are to increase the efficiency and transparency of research through the rapid dissemination of datasets and to facilitate their reuse.

**Email address of repository contact:**

**Year when repository started operating:**
2021

**DOI authority (if applicable):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by Swain-none** [comment]
Homepage URL of repository is no longer accessible
