### ISSUE TITLE
Add my Dataverse repository: KU Leuven RDR

### ISSUE THREAD

**Issue by DieuwertjeBloemen** [IQSS/dataverse-installations#111]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository:**
KU Leuven RDR

**Homepage URL of repository:**
https://rdr.kuleuven.be/

**Location of the repository (lat/long preferably or city or street address):**
Leuven, Belgium

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
RDR is the institutional research data repository created by KU Leuven in collaboration with LIBIS and Dataverse to help its researchers publish and share their research data.

**Email address of repository contact (won't be displayed on the map):**
rdr@kuleuven.be

**Year when repository started operating:**
2022

**DOI authority (if applicable; won't be displayed on the map):**
DataCite

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Thanks @DieuwertjeBloemen. KU Leuven RDR is added to the Dataverse map now.

<img width="734" alt="Screen Shot 2022-01-21 at 11 37 25 AM" src="https://user-images.githubusercontent.com/18374574/150565256-ea3ca88f-7176-49fc-b64d-4f89b4a4aa97.png">
