### ISSUE TITLE
Add my Dataverse repository: DADOS IPB

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#113]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository:**
DADOS IPB

**Homepage URL of repository:**
https://dados.ipb.pt

**Location of the repository (lat/long preferably or city or street address):**
41.79757744726813, -6.767712401768372

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
The data repository of the Instituto Politécnico de Bragança aims to store, preserve, share and manage research data generated by the academic community.

**Email address of repository contact (won't be displayed on the map):**

**Year when repository started operating:**
2022

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Hi @shlake. Could you try to run update_data.py to add this repository to the Dataverse map?

When I try, I get some kind of SSL certificate error when the line `response = urlrequest.urlopen(metrics_url)` runs and I'm wondering if this is an issue with my Python like last time or due to some change in the the "metrics_url" (https://dataversemetrics.odum.unc.edu/dataverse-metrics/config.json)

**Comment by shlake** [comment]
Need to update the python code for URL to:

 https://metrics.dataverse.org/ instead

I Will do soon.

**Comment by jggautier** [comment]
Thanks @shlake!

**Comment by shlake** [comment]
@jggautier 
Thanks to Don, I updated the python script with the new metrics URL.
and added the new site.

**Comment by pdurbin** [comment]
I just wanted to mention I was seeing those CERTIFICATE_VERIFY_FAILED errors too. I was looking at stuff like https://stackoverflow.com/questions/44649449/brew-installation-of-python-3-6-1-ssl-certificate-verify-failed-certificate to someday update my Python certificate store but for now changing the metrics URL works. Thanks!
