### ISSUE TITLE
Adding contact emails for several installations

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#118]
Hi @philippconzett, some of the contact email addresses you've added to [the Crowdsourced information about Dataverse installations spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo) look like they're from personal accounts. Is it okay to make those email addresses public?

**Comment by philippconzett** [comment]
@jggautier Sorry about that. I collected them from publicly available information on the web pages of Dataverse installations. I needed the addresses to send out the community survey the other day.

**Comment by jggautier** [comment]
Ah, no problem. Just wanted to be sure.
