### ISSUE TITLE
Add my Dataverse repository: FGV Dataverse

### ISSUE THREAD

**Issue by alsantiagoabreu** [IQSS/dataverse-installations#119]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository: FGV Dataverse

**Homepage URL of repository: https://dataverse.fgv.br/

**Location of the repository (lat/long preferably or city or street address): Centro Cultural FGV - Praia de Botafogo, 190 - Botafogo, Rio de Janeiro - RJ, 22250-900 , Brazil

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**

**Email address of repository contact (won't be displayed on the map):**
infra.acad@fgv.br and biblioteca.digital@fgv.br

**Year when repository started operating: 2021

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Hi @alsantiagoabreu. The FGV Dataverse should be added to the map today. Thanks!
