### ISSUE TITLE
Missing launch year Dataverse University of Milan

### ISSUE THREAD

**Issue by IlariaBelvedere** [IQSS/dataverse-installations#120]
Dataverse UNIMI was tested throughout 2018 and it was launched in 2019 according to this presentation (in English): https://www.eventi.garr.it/it/conf19/programma/materiali-conferenza-2018/presentazioni-4/391-conf19-presentazione-mornati/file.

**Comment by pdurbin** [comment]
@IlariaBelvedere thanks!

Relates to:

- #7
