### ISSUE TITLE
Missing launch year heiDATA

### ISSUE THREAD

**Issue by IlariaBelvedere** [IQSS/dataverse-installations#121]
About heiDATA, it seems that it was implemented in 2014 and maybe officially launched in 2015 (because this article from 2018 reports 2014 as the initial year and then "three years after the project started"): https://www.o-bib.de/bib/article/view/2018H2S61-71/6385
I can't read German, I only translated it, so it should be confirmed.

**Comment by pdurbin** [comment]
Related:

- #7
