### ISSUE TITLE
Missing launch year for Data INRAe

### ISSUE THREAD

**Issue by IlariaBelvedere** [IQSS/dataverse-installations#122]
From what I can read here (https://data.inrae.fr/): "Pour citer le portail : Institut National de Recherche pour l'Agriculture, l'Alimentation et l'Environnement. (2018). Data INRAE. INRAE. https://doi.org/10.14758/9T8G-WJ20", the installation was launched in 2018. There are also several youtube introductional videos from INRAE presenting the portal and they are dated four years ago: https://www.youtube.com/channel/UCdyST1LzXVP0Rh40-Ek4B_A.

**Comment by pdurbin** [comment]
Related:

- #7
