### ISSUE TITLE
Missing launch year for Peking University

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#124]
Let's go with 2014 based on https://dataverse.org/blog/q-peking-university-dataverse

"Peking University chose Dataverse for data repository in 2014 because Dataverse has the big advantage of being open source software... Peking University migrated to Dataverse 4.0 from Dataverse 3.3 in June 2015."

Related:

- #7

**Comment by IlariaBelvedere** [comment]
Great :) Thank you

**Comment by pdurbin** [comment]
@IlariaBelvedere sure! Do you like Python? Would you like to help update the map?

**Comment by IlariaBelvedere** [comment]
You mean as it is explained here: https://github.com/IQSS/dataverse-installations/blob/master/CONTRIBUTING.md? I can try to, If it all is required to update the map is running that script (because I am not really into programming and maybe I'll need help as well XD)!

**Comment by pdurbin** [comment]
@IlariaBelvedere yes, exactly. For this sub issue and the others we've opened, I went ahead and updated the map.

If you can continue to create sub issues, I'd appreciate it!

Also,  check out the ASCII art I added: https://github.com/IQSS/dataverse-installations/issues/7#issuecomment-1146606522 😄

**Comment by IlariaBelvedere** [comment]
Sure, I'll do what I can :)
