### ISSUE TITLE
Add darus.uni-stuttgart.de and dataverse.theacss.org to the map

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#14]
Two new installations have been added to the map at dataverse.org:

- https://darus.uni-stuttgart.de
- https://dataverse.theacss.org

Here's now that map looks now:

![Screen Shot 2019-10-22 at 10 27 06 AM](https://user-images.githubusercontent.com/21006/67296658-c520d800-f4b6-11e9-83c2-155bf2f1cf17.png)

Both installations should be added to the new map, which only has 48 installations and looks like this:

![Screen Shot 2019-10-22 at 10 27 09 AM](https://user-images.githubusercontent.com/21006/67296659-c520d800-f4b6-11e9-8cc3-70f49cf8af6a.png)

So far only @donsizemore @philippconzett and I know how to run `update-data.py` to update the map but if we work on #1 to improve README, anyone who has Python 3 installed can do this. I am very happy to coach anyone through the process! 😄

**Comment by pdurbin** [comment]
I just put a call out to the Dataverse community to help with this issue: https://groups.google.com/d/msg/dataverse-community/xFRXZ7BAuQA/Bve1-e5ACgAJ

**Comment by shlake** [comment]
@pdurbin I'll help with this one. Will need some help to get started. I have Python3 installed.

**Comment by pdurbin** [comment]
@shlake hooray! The first step is to go to https://github.com/IQSS/dataverse-installations and request edit access to the following spreadsheets:

- spreadsheet maintained by IQSS
- crowdsourced spreadsheet

**Comment by pdurbin** [comment]
@shlake you seem to have access now. Thanks! Are you comfortable with cloning this repo? The alternative is to download it as a zip if that's easier.

**Comment by shlake** [comment]
I've cloned this repo. Getting familiar with what's in it and how it works. I'll look over the other issues too.

**Comment by shlake** [comment]
@pdurbin new map has been created. Will write up documentation later, but am making a pull request the new data.json file

**Comment by pdurbin** [comment]
@shlake I just merged your pull request #15 and I'd like to thank you very much for making it!

Both installations are now at https://iqss.github.io/dataverse-installations/ (screenshots below):

![Screen Shot 2019-10-23 at 3 12 30 PM](https://user-images.githubusercontent.com/21006/67426289-c2ea7680-f5a7-11e9-9075-ddaca43577a9.png)

![Screen Shot 2019-10-23 at 3 13 46 PM](https://user-images.githubusercontent.com/21006/67426288-c2ea7680-f5a7-11e9-8ff3-46b7e411cbbf.png)

Thanks again! 🎉 🎉 🎉
