### ISSUE TITLE
Add my Dataverse repository: KEEN Dataverse

### ISSUE THREAD

**Issue by linsherpa** [IQSS/dataverse-installations#144]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository:**
KEEN Data Management Platform

**Homepage URL of repository:**
https://keen.zih.tu-dresden.de/

**Location of the repository (lat/long preferably or city or street address):**
Chemnitzer Straße 46 b
01187 Dresden, Germany

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
The KEEN Data Management Platform is a common central Data Management and Storage Platform for KEEN project.
(KEEN Project Link : http://keen-plattform.de/)

**Email address of repository contact (won't be displayed on the map):**
lincoln.sherpa@tu-dresden.de

**Year when repository started operating:**
2021

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.57826
**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Hi @linsherpa. The KEEN Data Management Platform appears on the map at dataverse.org now. Thanks!
