### ISSUE TITLE
Project board request for Cirad Dataverse

### ISSUE THREAD

**Issue by gwendoux** [IQSS/dataverse-installations#147]
**Name of installation:**
Cirad Dataverse

**URL of installation:**
https://dataverse.cirad.fr

**Comment by pdurbin** [comment]
@gwendoux I created a new board for Cirad at https://github.com/orgs/IQSS/projects/29

I made you "Admin" and you should be able to add additional people:

![Screen Shot 2022-06-23 at 3 30 27 PM](https://user-images.githubusercontent.com/21006/175382598-18dcc23c-ebcb-42d0-b64a-c946a76ff34e.png)

In 29458ed I added your new board to the map:

![Screen Shot 2022-06-23 at 3 35 40 PM](https://user-images.githubusercontent.com/21006/175382858-87676ce7-1278-4857-b71a-bf5cf038cfcb.png)

For @jggautier and @shlake, I also populated the `board_api` column. You can run a script to figure out what to put there:

```
$ python3 check-boards.py 
dataverse.cirad.fr created https://github.com/orgs/IQSS/projects/29 and "Project board API URL" should be updated to https://api.github.com/projects/14552642
```

@gwendoux I'm going to go ahead and close this issue but please let us know if you have any trouble using your new board. Thanks for requesting one!
