### ISSUE TITLE
Redape hostname doesn't resolve

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-installations#157]
The Redape Dataverse hostname entry: https://github.com/IQSS/dataverse-installations/blob/eae1111d82d6812717d83fbb39fea827b470a37c/data/data.json#L955

Should likely be `www.redape.dados.embrapa.br` instead.

**Comment by jggautier** [comment]
Is this a duplicate of https://github.com/IQSS/dataverse-installations/issues/156?

**Comment by donsizemore** [comment]
Looks like it got resolved in between my noticing, and opening the issue (I promise I looked before opening this one).
In any case, yes.
