### ISSUE TITLE
Add my Dataverse repository: Repositorio de Datos Académicos RDA-UNR

### ISSUE THREAD

**Issue by RDA-UNR** [IQSS/dataverse-installations#159]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository: Repositorio de Datos Académicos RDA-UNR**

**Homepage URL of repository: https://dataverse.unr.edu.ar/**

**Location of the repository (lat/long preferably; or street address; or city, country): -32.95019324385094, -60.63599686996669**

**Year when repository started operating: 2022**

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository: 
El Repositorio de Datos Académicos UNR (RDA-UNR) permite compartir, archivar, acceder, explorar y citar los datos de investigación gestionados por los docentes, investigadores  y alumnos de la UNR, con el fin de dar visibilidad a los datos, potenciando su acceso, su reutilización y garantizando su preservación a largo plazo.  Es un repositorio de auto publicación, en el cual los usuarios cargan, organizan, describen y publican sus datos. Cuentan para hacerlo con la ayuda de un equipo de curadores, guías y sesiones de entrenamiento.
The Academic Data Repository of the National University of Rosario (RDA- UNR) allows for sharing, storing, accessing, exploring, and citing research data managed by UNR professors, researchers and students so as to make these data visible and promote its use and reutilization, ensuring its long-term preservation. It is a self-publishing repository, i.e. users upload, organize, describe and publish their own data with the assistance of a team of curators, user guides and training sessions.
**

**Email address of repository contact (won't be displayed on the map): [repositoriodatos@unr.edu.ar](mailto:repositoriodatos@unr.edu.ar)**

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map): 10.57715**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Thanks! The repository should show up soon on the map on https://dataverse.org

**Comment by RDA-UNR** [comment]
Thank you!!! 


De: "Julian Gautier" ***@***.***> 
Para: "IQSS/dataverse-installations" ***@***.***> 
CC: "RDA-UNR" ***@***.***>, "Author" ***@***.***> 
Enviados: Viernes, 12 de Agosto 2022 15:58:09 
Asunto: Re: [IQSS/dataverse-installations] Add my Dataverse repository: Repositorio de Datos Académicos RDA-UNR (Issue #159) 





Thanks! The repository should show up soon on the map on [ https://dataverse.org/ | https://dataverse.org ]
