### ISSUE TITLE
Add my Dataverse repository: TRR170-DB

### ISSUE THREAD

**Issue by Abalduin-adm** [IQSS/dataverse-installations#160]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository:**
 TRR170-DB

**Homepage URL of repository:** 
https://planetary-data-portal.org/

**Location of the repository (lat/long preferably; or street address; or city, country):**
52.426911387040704, 13.356574494013994 , or Malteserstr. 74-100, 10785 Berlin, Germany

**Year when repository started operating:**
2020

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
The TRR170-DB was set up to manage data products of the collaborative research center TRR 170 'Late Accretion onto Terrestrial Planets' (https://www.trr170-lateaccretion.de/). However, meanwhile the repository also stores data by other institutions and researchers. Data include laboratory and other instrumental data on planetary samples, remote sensing data, geological maps and model simulations. 

**Email address of repository contact (won't be displayed on the map):**
elfrun.lehmann@fu-berlin.de, (abalduin@zedat.fu-berlin.de)

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.35003 - https://doi.org/10.35003

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**
https://www.re3data.org/repository/r3d100013520

**Comment by jggautier** [comment]
Thanks @Abalduin-adm! The repository should appear on the map today.

In the re3data entry at https://www.re3data.org/repository/r3d100013520, I didn't see a link to a [Core Trust Seal](https://www.coretrustseal.org/) application. Has the repository applied to that certification?

**Comment by jggautier** [comment]
Hi @Abalduin-adm. I'm going to mark this issue resolved. Please feel free to re-open if you'd like to add a link to a successful Core Trust Seal application or if the re3data entry at https://www.re3data.org/repository/r3d100013520 does include a link to a successful Core Trust Seal application and I just missed it.

**Comment by gitescire** [comment]
Hi @Abalduin-adm 
We request your support to add the following repository to the map:

**Name of repository:**
Tecnológico de Monterrey Data Hub

**Homepage URL of repository:**
https://datahub.tec.mx/

**Location of the repository (lat/long preferably; or street address; or city, country):**
25.6515649, -100.28954, Monterrey, Mexico

**Year when repository started operating:**
2021

_The following isn't required but is nice to have:_

**A short description (few sentences) about the repository:**
The Tecnológico de Monterrey's Data Hub offers Open Data generated by our researchers and other initiatives. This initiative is sponsored by both the Living Lab & Data Hub of the Institute for the Future of Education (IFE and the Tecnologico de Monterrey's Research Office. This repository is organized by Institutes and Schools.

**Email address of repository contact (won't be displayed on the map):**
[elfrun.lehmann@fu-berlin.de](mailto:elfrun.lehmann@fu-berlin.de), ([abalduin@zedat.fu-berlin.de](mailto:abalduin@zedat.fu-berlin.de))

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.57687- https://doi.org/10.57687

**Link to successful [Core Trust Seal](https://www.coretrustseal.org/) application:**
https://www.re3data.org/repository/r3d100014156  (We are still in the process of obtaining the certificate Core)

Thank you in advance
Yours faithfully,

Brigitte Sebastian, eScire.

**Comment by pdurbin** [comment]
@gitescire hi! Can you please create a new issue? Thanks! ❤️
