### ISSUE TITLE
Add my Dataverse repository: {DATICE}

### ISSUE THREAD

**Issue by sindribaldur** [IQSS/dataverse-installations#164]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository:**
DATICE

**Homepage URL of repository:**
[DATICE](https://dataverse.rhi.hi.is/)

**Location of the repository (lat/long preferably; or street address; or city, country):**
64.14042,-21.9493

**Year when repository started operating:**
2020

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
DATICE is a data service and archive for Icelandic social science research data

**Email address of repository contact (won't be displayed on the map):**
felagsvisindastofnun@hi.is

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by shlake** [comment]
@jggautier my turn, I got this one.
