### ISSUE TITLE
Add my Dataverse repository: Repositorio de datos de la Universidad de Concepción

### ISSUE THREAD

**Issue by ElvisAravena** [IQSS/dataverse-installations#173]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository:**

Repositorio de datos de la Universidad de Concepción

**Homepage URL of repository:**
https://datav.udec.cl

**Location of the repository (lat/long preferably; or street address; or city, country):**
-36.832267682667116, -73.03503216931071
Barrio Universitario S/N
Concepción
Chile

**Year when repository started operating:**
2022

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
El repositorio de Datos de la Universidad de Concepción, tiene como objetivo conservar, visibilizar y poner a disposición los datos y/o complementos de información utilizada en los proyectos de investigación por nuestros académicos y/o investigadores.

**Email address of repository contact (won't be displayed on the map):**

bibliotecas@udec.cl

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.48665

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Thanks for the info @ElvisAravena! We'll get this added as soon as possible, probably today or tomorrow.

**Comment by jggautier** [comment]
Hi @ElvisAravena. Repositorio de datos de la Universidad de Concepción should appear on the map at dataverse.org today, and eventually we'll attempt to add information about it to the metrics page at https://dataverse.org/metrics

**Comment by ElvisAravena** [comment]
Thank you very much Julian.
