### ISSUE TITLE
Project board request for KU Leuven RDR

### ISSUE THREAD

**Issue by DieuwertjeBloemen** [IQSS/dataverse-installations#177]
**Name of installation:**
KU Leuven RDR

**URL of installation:**
https://rdr.kuleuven.be/

**Comment by shlake** [comment]
@pdurbin let me try this one. 

You sent instructions, let me see if I can do it. Will try this afternoon.

**Comment by pdurbin** [comment]
@shlake sure! If you get stuck because you need more access, I'm happy to give it to you! Please create a "classic" board because I don't know if the new boards work with my script.

**Comment by shlake** [comment]
@pdurbin trying to add this now (this morning), per your instructions #175 ... how do I know what # board to add to the spreadsheet?

Your instructions: "FYI after I add the board to the spreadsheet (under the board column)"

**Comment by shlake** [comment]
OK, @pdurbin I figured out how to see all current boards and their numbers. I will add the next number in sequence.

**Comment by shlake** [comment]
But I get an error, maybe I cannot create the board on IQSS? 

```
$ python3 check-boards.py
Traceback (most recent call last):
  File "check-boards.py", line 32, in <module>
    board_api_url = api_url_by_html_url[board_html_url]
KeyError: 'https://github.com/orgs/IQSS/projects/39'
```

**Comment by pdurbin** [comment]
@DieuwertjeBloemen your new board is https://github.com/orgs/IQSS/projects/39

I made you admin. Do you want any other admins, such as @ErykKul or others? Thanks.

**Comment by DieuwertjeBloemen** [comment]
Thanks to both of you for setting this up. I don't think there's an immediate need for anyone else to be admin for the boards, as we'll be setting the boards up together and they can move things around in the boards without being admin, right? Otherwise, it would be @ErykKul @okaradeniz and @Kris-LIBIS that should be added as admins to ensure they can add items and move items in and between the boards.

**Comment by Kris-LIBIS** [comment]
Only Dieuwertje as admin should be fine.

**Comment by pdurbin** [comment]
I went ahead and made all four of you admins. Have fun! I'll go ahead and close this but please let us know if you need anything!
