### ISSUE TITLE
Missing CoreTrustSeal data

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#179]
As of 5475658 the following CoreTrustSeal links are in data.json:

- https://www.coretrustseal.org/wp-content/uploads/2018/02/Australian-Data-Archive.pdf
- https://www.coretrustseal.org/wp-content/uploads/2018/04/Tilburg-University-Dataverse.pdf
- https://www.coretrustseal.org/wp-content/uploads/2020/03/DataverseNO.pdf
- https://www.coretrustseal.org/wp-content/uploads/2018/11/Qualitative-Data-Repository.pdf
- https://www.coretrustseal.org/wp-content/uploads/2020/10/Odum-Institute-Data-Archive.pdf

However, the [2022 survey](https://groups.google.com/g/dataverse-community/c/gI7vJRNqrPw/m/Iyp47y3SAwAJ) conducted by @philippconzett says there should be five links from the 34 installations surveyed which do not include Odum/UNC (they didn't take the survey, in other words). So there's a missing CTS link we should add. But for which installation? 😄 (Note that Tilburg is part of DataverseNL which took the survey.)

**Comment by philippconzett** [comment]
As far as I can tell from the raw data from the survey (), the missing CoreTrustSeal file is from AUSSDA (https://data.aussda.at/); cf. [
As far as I can tell from the raw data from the survey (), the missing CoreTrustSeal file is from AUSSDA (https://data.aussda.at/); cf. https://www.coretrustseal.org/wp-content/uploads/2020/07/AUSSDA-The-Austrian-Social-Science-Data-Archive.pdf.](https://www.coretrustseal.org/wp-content/uploads/2020/07/AUSSDA-The-Austrian-Social-Science-Data-Archive.pdf).

**Comment by pdurbin** [comment]
@philippconzett great find! Thanks!

@shlake or @jggautier (or @philippconzett !), do you want to make a PR to add it?

**Comment by shlake** [comment]
I got it.

**Comment by pdurbin** [comment]
Thanks, @shlake! You're the best!

By the way, I talked to @philippconzett and he's not a Python person. 😄

**Comment by shlake** [comment]
I pretend to be... know enough to get myself in trouble.... as long as the command "python3 update-data.py" works - I'm good 😉
