### ISSUE TITLE
Proposing Making Installation Info docs (both) be editable by all

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse-installations#18]
Per issue #17 
I suggest that the google spreadsheets

- [spreadsheet maintained by IQSS](https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk/edit?usp=sharing)
- [crowdsourced spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo/edit#gid=0)

Both be editable by all, or at least the crowsdsourced one. 

The info on the maps doesn't get changed unless the script is run. The person who runs the script - is the person to verify new information in the spreadsheets.

Yes? Less stuff for IQSS to be involved in, especially since @shlake is writing up documentation for updating the map

**Comment by pdurbin** [comment]
@shlake yes! You've got it exactly right. The data.json file is regenerated by the Python script when you run it, pulling from multiple data sources. There are more than the two above. Are you comfortable looking at the script to see the rest? Or should I document them in the README?

**Comment by shlake** [comment]
@pdurbin I don't mind looking at the script.
I was also thinking if both files were made editable, then why have two files? (maybe another issue since the code would have to change?)

I can certainly add info on inputs/outputs to the README. I'm geeky about documentation ;-)

**Comment by pdurbin** [comment]
@shlake well, I like your idea of only making the "crowdsourced" spreadsheet publicly editable for now. Is that ok. Do you have the right access to make that change? Eventually I want many of the data sources (multiple spreadsheets and a JSON feed) to melt away.

The reason I have so few columns in the "crowdsourced" spreadsheet is that I'd like us to fill in the fields for launch year (#7) and any missing descriptions, especially launch year. My thought was to focus energy there first but it it makes sense to start adding new columns now, especially for #16, that's totally fine!

> I can certainly add info on inputs/outputs to the README. I'm geeky about documentation ;-)

Perfect. I'm going to assign #1 to you. Thanks!! 😄 🎉 🚀

**Comment by shlake** [comment]
@pdurbin I was able to make the Crowdsourced spreadsheet editable by "ALL". 
Will keep maintained by IQSS as is, not editable by all, but editable by those who ask (and we know 😄)

**Comment by pdurbin** [comment]
@shlake cool. I hope nobody trashes it! At least we can re-create it, if necessary, from data.json. 😄
