### ISSUE TITLE
Add my Dataverse repository: NYCU Dataverse

### ISSUE THREAD

**Issue by twtw** [IQSS/dataverse-installations#181]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository:**
NYCU Dataverse

**Homepage URL of repository:**
https://dataverse.lib.nycu.edu.tw

**Location of the repository (lat/long preferably; or street address; or city, country):**
24.7867714, 120.9984256
National Yang Ming Chiao Tung University Library
No. 1001, Daxue Rd. East Dist., Hsinchu City 300093, Taiwan (ROC)

**Year when repository started operating:**
2022

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
NYCU Dataverse is the institutional research data repository of the National Yang Ming Chiao Tung University. This repository is aimed to share, archive, preserve, cite, access, and explore research data produced in the university. Datasets deposited to the NYCU Dataverse and published are automatically given a citation and a persistent link, increasing the researcher's impact, and visibility of research.

**Email address of repository contact (won't be displayed on the map):**
RDM@lib.nycu.edu.tw

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.57770

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by pdurbin** [comment]
@twtw thanks for providing all the information! @shlake added your installation to the map (thanks, Sherry!) and it looks like this:

![Screen Shot 2023-01-04 at 1 45 02 PM](https://user-images.githubusercontent.com/21006/210629907-bd30553d-cf31-42a3-89f3-36628c546da3.png)

You are also welcome to have a project board for your installation if you like. Please use the issue template if you'd like to request one.
