### ISSUE TITLE
Project board request for JPL Open Repository

### ISSUE THREAD

**Issue by ar062800** [IQSS/dataverse-installations#186]
**Name of installation:**
JPL Open Repository

**URL of installation:**
https://dataverse.jpl.nasa.gov/

**Comment by pdurbin** [comment]
I created https://github.com/orgs/IQSS/projects/42 , made @ar062800 the admin of it, and walked him through creating columns and adding issues.

I also ran the "check boards" scrpt and added https://api.github.com/projects/14658833 to the spreadsheet for the next time I run an aggregation.
