### ISSUE TITLE
Add SciELO Data to the map

### ISSUE THREAD

**Issue by marinachagas** [IQSS/dataverse-installations#189]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository: SciELO Data

**Homepage URL of repository: https://data.scielo.org/

**Location of the repository (lat/long preferably; or street address; or city, country): -23.593676091704516, -46.643770082114585 (R. Dr. Diogo de Faria, 1087 - Vila Clementino, São Paulo - SP, 04037-003 Brasil.

**Year when repository started operating: 2020

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository: SciELO Data is a multidisciplinary repository for deposition, preservation and dissemination of research data from articles submitted and approved for publication, already published in SciELO Network journals or deposited in SciELO Preprints.

**Email address of repository contact: data@scielo.org

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map): 10.48331

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Thanks @marinachagas! SciELO Data is now added to the map at https://dataverse.org.

<img width="733" alt="Screen Shot 2023-02-24 at 5 26 33 PM" src="https://user-images.githubusercontent.com/18374574/221305474-d2928dd3-5974-4fce-b4ae-a307be750bb4.png">
