### ISSUE TITLE
Add my Dataverse repository: bonndata

### ISSUE THREAD

**Issue by sergejzr** [IQSS/dataverse-installations#191]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
bonndata

**Homepage URL of repository:**
https://bonndata.uni-bonn.de/

**Location of the repository (lat/long preferably; or street address; or city, country):**
50.728944161796164, 7.08860672727616

Wegeler Strasse 6
53123 Bonn, Germany

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
bonndata is a state-of-the-art, cross-disciplinary research data repository designed for scientists at the University of Bonn. The repository is an integral part of the University of Bonn's research infrastructure and it is maintained by the Research Data Service Center, which offers a range of services to help researchers manage their data throughout the research lifecycle. 

**Email address of repository contact:**
szerr@uni-bonn.de

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Thanks @sergejzr. bonndata should be added to the map in a few minutes.
