### ISSUE TITLE
dataverse.sta.uwi.edu switched to Dryad

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-installations#194]
per https://researchdata.wisc.edu/data-repositories/

**Comment by shlake** [comment]
Yes, to be removed, but

The domain "sta.uwi.edu" is the University of the West Indies, not University of Wisconsin - Madison.

And they are using CKAN now: https://sta.uwi.edu/rdifund/projects/agrinett/openData.asp

**Comment by donsizemore** [comment]
sounds good.
