### ISSUE TITLE
https://research-data.ifsttar.fr is in a questionable state

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-installations#196]
should we keep it?

**Comment by pdurbin** [comment]
Yeah, https://research-data.ifsttar.fr is only showing Glassfish... Dataverse isn't deployed:

![Screen Shot 2023-05-03 at 3 08 56 PM](https://user-images.githubusercontent.com/21006/236019378-502fc076-265f-4ed4-b590-f8ea4eb1902f.png)

**Comment by pdurbin** [comment]
I emailed the address I found in https://help.hmdc.harvard.edu/Ticket/Display.html?id=218379

That ticket is from 2015. It's the only contact I could find.

**Comment by jggautier** [comment]
Did some looking around and found a repository at https://data.univ-gustave-eiffel.fr whose datasets' DOIs have the same authority that we recorded for this installation, 10.25578.

So maybe the institute moved their datasets to a university's Dataverse installation?

https://data.univ-gustave-eiffel.fr isn't on the Dataverse map and I couldn't find any emails or conversation online between us and them. There's more info about this installation at https://www.univ-gustave-eiffel.fr/en/research/open-science/open-source-data-and-software, including a contact email, research-data@univ-eiffel.fr.

@pdurbin, could you email that repository to ask if https://data.univ-gustave-eiffel.fr has been shut down, if the institute is using this installation now, and if we can add https://data.univ-gustave-eiffel.fr to the Dataverse map?

**Comment by jggautier** [comment]
Or I can email this https://data.univ-gustave-eiffel.fr to ask. Just let me know.

**Comment by pdurbin** [comment]
@jggautier please go ahead! Thanks!

**Comment by jggautier** [comment]
Okay, I emailed research-data@univ-eiffel.fr today and CC'ed you.

**Comment by pdurbin** [comment]
To summarize an email received today by me and @jggautier (thanks for initiating this, Julian):

- datasets were in fact moved from Ifsttar to Gustave
- Gustave plans to move all datasets to the national repo: https://entrepot.recherche.data.gouv.fr

I'm thinking we should simply remove Ifsttar from the map. However, for better optics, perhaps we could wait until we add another installation first since we're at exactly 100 as of this writing. Or we could drop to 99. No strong preference.

**Comment by jggautier** [comment]
I think we should remove Ifsttar now, add the Gustave installation, and remove it when it shuts down at the end of the year. 

This way the map is as accurate as we can make it and it'll be at at least 100 for the 6 or so months. And it's possible we'll add other installations before then.

What do you think? If you agree I can ask the folks at the Gustave installation if we can add their installation.
