### ISSUE TITLE
Add my Dataverse repository: Papyrus

### ISSUE THREAD

**Issue by PaulaSaav** [IQSS/dataverse-installations#197]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:** PAPYRUS

**Homepage URL of repository:** https://papyrus-datos.co/

**Location of the repository (lat/long preferably; or street address; or city, country):**  COLOMBIA

**Year when repository started operating:** 2022

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
Papyrus is a multidisciplinary data repository, which houses the scientific data sets of research projects carried out by the Colombian institutions belonging to the Colombia Consortium, whose purpose is to give the data visibility, guarantee their preservation and facilitate their access, retrieval and reuse through centralized custody and management.

**Email address of repository contact:** consortia@papyrus-datos.com

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):** 10.57924

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by shlake** [comment]
Since this is a consortium, I used the general "Columbia" lat/long
