### ISSUE TITLE
Add my Dataverse repository: Tecnológico de Monterrey Data Hub

### ISSUE THREAD

**Issue by gitescire** [IQSS/dataverse-installations#198]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
Tecnológico de Monterrey Data Hub

**Homepage URL of repository:**
https://datahub.tec.mx/

**Location of the repository (lat/long preferably; or street address; or city, country):**
25.6515649, -100.28954, Monterrey, Mexico

**Year when repository started operating:**
2021

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
The Tecnológico de Monterrey's Data Hub offers Open Data generated by our researchers and other initiatives. This initiative is sponsored by both the Living Lab & Data Hub of the Institute for the Future of Education (IFE and the Tecnologico de Monterrey's Research Office. This repository is organized by Institutes and Schools.

**Email address of repository contact:**
research.datahub@servicios.tec.mx

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.57687- https://doi.org/10.57687

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**
https://www.re3data.org/repository/r3d100014156 (We are still in the process of obtaining the certificate Core)

Thank you in advance
Yours faithfully,

**Comment by shlake** [comment]
@gitescire Please let us know when you have your Core Trust Seal document and we will link to that.

Adding repo to the map now.

**Comment by gitescire** [comment]
Hello @shlake 
Thank you very much for your support. So, I understand that I can already see my repository on the map or I have to wait a certain time and then when I have my document the link is added, is that correct?

Thank you in advance :)

**Comment by shlake** [comment]
@gitescire your repository will be on the map soon, no need to wait for Core Trust Seal document.

I just ran into a github pages display problem, one I created. Working on the fix.

**Comment by gitescire** [comment]
@shlake Great! Thank you very much 👍 
I remain attentive if you require anything from us.

**Comment by gitescire** [comment]
@shlake thank you very much for your support, the repository already appears on the map 🎉 
But when I click on the title an error appears when opening the page, I have checked the repository [**page**](https://datahub.tec.mx) and it is online. Do we need to make a configuration?

**Comment by pdurbin** [comment]
@gitescire hi! Would it be possible for you to set up a redirect from http://datahub.tec.mx to https://datahub.tec.mx ? That should fix it.

Here's what I see for your site:

```
% curl -i http://datahub.tec.mx 
curl: (28) Failed to connect to datahub.tec.mx port 80 after 75007 ms: Couldn't connect to server
```

This is what I'm asking for, if possible (a redirect to an https location):

```
% curl -i http://demo.dataverse.org
HTTP/1.1 302 Found
Date: Thu, 25 May 2023 01:04:24 GMT
Server: Apache/2.4.37 (rocky) OpenSSL/1.1.1k mod_apreq2-20101207/2.8.1
Location: https://demo.dataverse.org/
Content-Length: 211
Content-Type: text/html; charset=iso-8859-1
```
