### ISSUE TITLE
Update the name of my Dataverse repository: {Johns Hopkins Research Data Repository}

### ISSUE THREAD

**Issue by bgunia** [IQSS/dataverse-installations#200]
Hi, our repository is already on the map, but our name has changed from the Johns Hopkins University Data Archive to the Johns Hopkins Research Data Repository. Could you please update? https://archive.data.jhu.edu/
Thanks!
Betsy

**Comment by pdurbin** [comment]
@bgunia hi! I fixed the name but before I close this, would you like a better description than "Johns Hopkins Research Data Repository" (a repeat of your name)?

You can see a list of other descriptions at https://dataverse.org/installations

**Comment by bgunia** [comment]
Thanks!

Sure, let's update our description to something actually descriptive :)

"The Johns Hopkins Research Data Repository is an open access repository for Johns Hopkins researchers to share their research data. It is administered by professional curators at JHU Data Services, who will work with depositors to enable future discovery and reuse of your data."

**Comment by pdurbin** [comment]
@bgunia you've got it! Please take a look at https://dataverse.org/installations
