### ISSUE TITLE
Change JPL Open Repository contact email

### ISSUE THREAD

**Issue by ant-reyes** [IQSS/dataverse-installations#206]
Hello! Can the JPL Open Repository contact email be changed to library@jpl.nasa.gov please?

**Comment by jggautier** [comment]
Email's changed in [the spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo) and [the JSON](https://github.com/IQSS/dataverse-installations/blob/main/data/data.json).
