### ISSUE TITLE
solo.mapbiomas.org no longer resolves in DNS

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-installations#212]
Has it gone away?

**Comment by anjosmarcos** [comment]
Hello, @donsizemore 
Yes, we've recently made an update, and now the service is available at a new URL: https://soildata.mapbiomas.org/. You can access it there. Thank you for your understanding!

**Comment by jggautier** [comment]
I updated the URL of SoilData.

@donsizemore, should I close this issue or is there anything else we need to do before then?

**Comment by jggautier** [comment]
I'm going to close this GitHub issue since the URL we use for the map and metrics has been updated.
