### ISSUE TITLE
Add my Dataverse repository: {RODBUK}

### ISSUE THREAD

**Issue by JacekChudzik** [IQSS/dataverse-installations#214]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
RODBUK

**Homepage URL of repository:**
https://rodbuk.pl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
50°04'08.3"N 19°54'33.6"E
Krakow, Poland

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**

RODBUK Cracow Open Research Data Repository was founded on the initiative of Board of Directors of the Cracow Library Group. The purpose of RODBUK is to collect, develop, archive and make available in open access all types of research data created by researchers, PhD candidates and students in the course of scientific activity. RODBUK is co-created by six Cracow universities:
 • AGH University of Science and Technology,
 • University of Physical Education in Krakow,
 • Cracow University of Technology,
 • Krakow University of Economics,
 • Jagiellonian University in Kraków,
 • Pedagogical University of Krakow.

**Comment by jggautier** [comment]
Thanks @JacekChudzik!

This is interesting. So RODBUK is only to harvest metadata from 6 other Dataverse installations. At least that's what I understood from our emails.

But you would like only RODBUK to appear on the Dataverse map, and we should not add the other 6 installations to the Dataverse map at dataverse.org?

Usually, we use the map to show all Dataverse installations, even those that only index datasets that are published in other repositories, like [ODISSEI Portal](https://portal.odissei.nl/dataverse/odissei-portal).

**Comment by shlake** [comment]
Hi @jggautier , not necessarily related to adding this installation....

But I am interested in how the Zenodo datasets have been harvested. I have been wanting to do something similar with Dryad.

This dataset is harvested (I think) where the DOI goes to Zenodo: https://uj.rodbuk.pl/dataset.xhtml?persistentId=doi:10.5281/zenodo.8189733

I see the "new" API information on Harvesting in the guides: https://guides.dataverse.org/en/latest/api/native-api.html#managing-harvesting-server-and-sets

But I think I am missing the part where the remote site (Zenodo in this case) creates the OAI-PMH endpoint (server-side). How is that done?

I'm happy to post this to the Google Group, but if you have info you can point me to, I'd appreciate that. Thanks.

**Comment by jggautier** [comment]
@shlake, I'm not sure that Dataverse's OAI-PMH feature was used to harvest that dataset. If it was, the harvested dataset wouldn't have its own page. And I'd expect the card on the [search results](https://uj.rodbuk.pl/dataverse/chemia/?q=%22Understanding+and+controlling+spatial+resolution%22) to have that harvesting symbol.

I'd guess that whatever was done for this dataset is similar to what the folks at ODISSEI Portal are doing to index datasets from other repositories.

**Comment by jggautier** [comment]
But could you post in the Dataverse Google Group about using OIA-PMH to harvest sets from Zenodo? I think you still have unanswered questions right?

**Comment by shlake** [comment]
I asked last year: https://groups.google.com/g/dataverse-community/c/9JGlkUfNsPU/m/JKJ8wyHwAwAJ

But I can ask again. In Eugene's example - datasets were "ingested" from Dryad, all metadata and the files and a new DOI (Borealis DOI) is issued.

I would like just to harvest the metadata, and not generate a new DOI - like the OAI-PMH harvesting does between Dataverse repositories.

The example in RODBUK - is "similar" to harvesting, only metadata, no files and the DOI goes to the original record in Zenodo. But as you pointed out, there seems to be a local metadata record created (a new landing page - per se).

**Comment by JacekChudzik** [comment]
@jggautier Of course, I can add all 6 repos + harvester. Should I do it here?

@shlake I don't think I can help you. We are not harvesting from Zenodo. The data has been only migrated to uj.rodbuk.pl. This migrated dataset is harvested to rodbuk.pl.

**Comment by jggautier** [comment]
Yes please, feel free to do it here @JacekChudzik :)

Then I'll add them to the map.

**Comment by JacekChudzik** [comment]
**Name of repository:**
RODBUK UJ

**Homepage URL of repository:**
https://uj.rodbuk.pl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
50°03′41″N 19°55′21″E
Krakow, Poland

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
RODBUK Cracow Open Research Data Repository enables Jagiellonian University researchers, doctoral students and postdoctoral fellows pursuing research projects to deposit, archive and make publicly available data from various disciplines and in various formats. Each dataset that is deposited in the repository will be automatically assigned a DOI identifier. Use of RODBUK for users is fully free of charge.

**Comment by JacekChudzik** [comment]
**Name of repository:**
RODBUK AGH

**Homepage URL of repository:**
https://agh.rodbuk.pl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
50.06563519129485, 19.921664978520116
Krakow, Poland

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
RODBUK Cracow Open Research Data Repository enables AGH University of Krakow researchers, doctoral students and postdoctoral fellows pursuing research projects to deposit, archive and make publicly available data from various disciplines and in various formats. Each dataset that is deposited in the repository will be automatically assigned a DOI identifier. Use of RODBUK for users is fully free of charge.

**Comment by JacekChudzik** [comment]
**Name of repository:**
RODBUK PK

**Homepage URL of repository:**
https://pk.rodbuk.pl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
50.0710379263687, 19.94238992887635
Krakow, Poland

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
RODBUK Cracow Open Research Data Repository of Cracow University of Technology is used to collect, store and publicly share research data created during scientific works and research projects carried out by the CUT scientific staff. RODBUK is open to all scientific units interested in depositing and sharing their research data. RODBUK usage is free of charge.

**Comment by JacekChudzik** [comment]
**Name of repository:**
RODBUK UEK

**Homepage URL of repository:**
https://uek.rodbuk.pl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
50.06870903437973, 19.956188749650988
Krakow, Poland

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
RODBUK - Cracow Open Research Data Repository of the Krakow University of Economics collects, archives and makes available in open access research data created during scientific works and research projects carried out by research staff and doctoral students of KUE. Each dataset placed in the Repository will be automatically assigned a DOI identifier. All published metadata will meet the guidelines provided by OpenAIRE. FAIR principles are applied in the Repository. The use of the Repository is free of charge.

**Comment by JacekChudzik** [comment]
@jggautier I added four instances (four Krakow universities) + there is harvester instance (rodbuk.pl) which I described in the first post. Last 2 are running, but there is no data stored on them yet and we thought that maybe we'll wait with adding tham at least till first dataset will be published.

**Comment by jggautier** [comment]
Great! Thanks @JacekChudzik. We'll add these installations as soon as possible!
