### ISSUE TITLE
Add my Dataverse repository: Concorda

### ISSUE THREAD

**Issue by pallinger** [IQSS/dataverse-installations#216]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
Concorda

**Homepage URL of repository:**
https://science-data.hu

**Location of the repository (lat/long preferably; or street address; or city, country):**
Budapest, Hungary (cannot give a concrete lat/long pair, as it is multi-site)

**Year when repository started operating:**
2020

**A short description (few sentences) about the repository:**
The Concorda repository was originally created as an ad-hoc initiative for data exchange during the Covid-19 pandemic by SZTAKI and WIGNER research institutes. Since then, the repository was significantly expanded with additional disk space and other resources donated by SZTAKI and WIGNER, and accepts data from all Hungarian researchers (with some storage constraints). In 2021, the ARP project started to build research data infrastructure for the Hungarian Research Network, and chose Concorda as the main repository component to be integrated, while also significantly expanding its storage capacity.

See also:
https://science-research-data.hu/
https://fairsharing.org/4585
https://www.re3data.org/repository/r3d100014109
https://v2.sherpa.ac.uk/id/repository/10638

**Email address of repository contact:**
concorda-admin@dsd.sztaki.hu

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
We do not use DOI right now, we use the handle authority/shoulder "21.15109/CONCORDA" currently.

**Comment by jggautier** [comment]
Thanks @pallinger!

Your point about being multi-site and not having a lat/long to give makes sense to me. I've brought up similar points about other installations we've added on [Dataverse.org](https://dataverse.org)'s online map, which requires a lat/long to add points. And in some cases we chose a lat/long that represents where the installation is administered, knowing that the location isn't very precise.

As far as I know, people are mainly using this information to get a sense of the representation of Dataverse around the world, to celebrate the use of Dataverse in new areas, and connect people who are interested in Dataverse with folks who are using it in their parts of the world.

Would it be okay if we pick a lat/long that points to the Institute for Computer Science and Control where I think SZTAKI is based? Google Maps tells me that would be 47.48036160998325, 19.05187656215667.

I think this would let the Dataverse community know that there's now a Dataverse installation based in Hungary.

**Comment by pdurbin** [comment]
The FIRST in Hungary! 🇭🇺 Exciting! 🎉

**Comment by pallinger** [comment]
> Would it be okay if we pick a lat/long that points to the Institute for Computer Science and Control where I think SZTAKI is based? Google Maps tells me that would be 47.47834443024498, 19.052104232575363.

This would be OK, it corresponds to neither of the three actual locations :) .

**Comment by jggautier** [comment]
Okay, Concorda's added! Thanks for letting us add it and congrats on all of the expansions!
