### ISSUE TITLE
Add my Dataverse repository: DANS Data Station Social Sciences and Humanities

### ISSUE THREAD

**Issue by LauraHuisintveld** [IQSS/dataverse-installations#217]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
DANS Data Station Social Sciences and Humanities

**Homepage URL of repository:**
https://ssh.datastations.nl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
latitude 52.0705, longitude 4.3007 (The Hague, The Netherlands)

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
The Data Station Social Sciences and Humanities is a service of DANS. It allows you to deposit and search for data within the social sciences and humanities. 

**Email address of repository contact:**
info@dans.knaw.nl

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.17026

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**
(No yet)

**Comment by jggautier** [comment]
Added! Thanks @LauraHuisintveld!
