### ISSUE TITLE
Change 'About URL' and 'harvesting sets' information for DataverseNL

### ISSUE THREAD

**Issue by LauraHuisintveld** [IQSS/dataverse-installations#218]
Can the information in the 'Crowdsourced information about Dataverse installations'  and the map for DataverseNL be updated?
The _About URL_ should be changed into: https://dans.knaw.nl/en/data-services/dataversenl/
The _harvesting set_ 'uvt_datasets' can be removed from the list. 

Kind regards,
Laura Huis in 't Veld
DANS

**Comment by jggautier** [comment]
Done! Thanks @LauraHuisintveld!
