### ISSUE TITLE
lida.dataverse.lt appears to be down

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#221]
This was reported by Jorrit Poelen from UCSB, who left comments on [the Crowdsourced information about Dataverse installations](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo).

I'm not sure why or what exactly isn't working. Feel free to retitle this issue if URL no longer resolves in DNS, as @donsizemore reported in other issues like https://github.com/IQSS/dataverse-installations/issues/212

**Comment by pdurbin** [comment]
It's still in DNS:

```
$ host lida.dataverse.lt
lida.dataverse.lt has address 158.129.0.22
```

However, it's timing out:

```
$ curl lida.dataverse.lt
curl: (7) Failed to connect to lida.dataverse.lt port 80 after 6172 ms: Couldn't connect to server
```

It looks like it was added here:

- #104

@vaidasmo you helped add LiDA to the map. Do you have any more information about its status?

(It looks like we could also email data@ktu.lt)

**Comment by vaidasmo** [comment]
Our university had a huge cyberattack. So the archive servers are still down. We hope to be back and operational towards the end of the next week.

**Comment by pdurbin** [comment]
@vaidasmo oh no! Hang in there!

**Comment by vaidasmo** [comment]
Just wanted to inform, that lida.dataverse.lt was restored and is operational again :-)

**Comment by jggautier** [comment]
Thanks for letting us know @vaidasmo. I'm going to close this issue then.
