### ISSUE TITLE
Add my Dataverse repository: IDSC

### ISSUE THREAD

**Issue by DominikWA** [IQSS/dataverse-installations#222]
All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated

Name of repository:
IDSC Dataverse

Homepage URL of repository:
https://dataverse.iza.org/

Location of the repository (lat/long preferably; or street address; or city, country):
Bonn, Germany - 50.73005292856627, 7.109468014101816

Year when repository started operating:
2024

A short description (few sentences) about the repository:
The IDSC Dataverse is the Data Repository of the IDSC - International Data Service Center of IZA - Institute of Labor Economics. It was created as part of a project sponsored by the German Federal Ministry of Education and Research whose aim was to produce building blocks for research data trustees. The purpose of the IDSC Dataverse is to serve the needs of  researchers and entities associated with IZA and make datasets available for replication, secondary research and teaching purposes. It adheres to the FAIR data principles. 

See also:
https://www.iza.org
https://idsc.iza.org

Email address of repository contact:
idsc@iza.org

DOI authority (such as 10.26193; if applicable; won't be displayed on the map):
10.15185

**Comment by jggautier** [comment]
Thanks for adding the installation @shlake!
