### ISSUE TITLE
Add my Dataverse repository: DANS Data Station Physical and Technical Sciences

### ISSUE THREAD

**Issue by CeesH** [IQSS/dataverse-installations#225]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository: DANS Data Station Physical and Technical Sciences**

**Homepage URL of repository: https://phys-techsciences.datastations.nl**

**Location of the repository (lat/long preferably; or street address; or city, country): 52.0705/4.3007**

**Year when repository started operating: 2023**

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository: Domain-specific data repository for research data from the Physical and Technical sciences. This repository focuses on the Dutch research community, offering repository services to organisations and individuals that have no (direct) acces to an institutional repository, or have a preference for the multi-disciplinary data services provided by DANS. **

**Email address of repository contact: info@dans.knaw.nl**

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map): 10.17026**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Thanks @CeesH! DANS Data Station Physical and Technical Sciences is now on the map at https://dataverse.org
