### ISSUE TITLE
Add my Dataverse repository: BioData.pt Data Management Portal (DMPortal)

### ISSUE THREAD

**Issue by GilOliveira** [IQSS/dataverse-installations#226]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
BioData.pt Data Management Portal (DMPortal)

**Homepage URL of repository:**
https://dmportal.biodata.pt

**Location of the repository (lat/long preferably; or street address; or city, country):**
38°44'12"N, 9°8'20"W

Instituto Superior Técnico, University of Lisbon - Av. Rovisco Pais, Lisbon, Portugal

**Year when repository started operating:**
2020

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
DMPortal is offered by BioData.pt, the Portuguese biological data infrastructure and national node of ELIXIR. The portal aims to support the national life sciences research community by enabling FAIR research practices. DMPortal is open to all life sciences fields, but has traditionally been more focused in supporting research in COVID-19, human health, and plant sciences.

**Email address of repository contact:**
dm.portal@biodata.pt

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.34636

**Comment by jggautier** [comment]
BioData.pt Data Management Portal (DMPortal) has been added to the Dataverse map. Thanks @GilOliveira!
