### ISSUE TITLE
Add my Dataverse repository: uken and awf from rodbuk.pl family

### ISSUE THREAD

**Issue by JacekChudzik** [IQSS/dataverse-installations#227]
Dear @jggautier I would like to inform you about next two Dataverses repos from RODBUK family. First one (uken.rodbuk.pl) runs on a Crossref as DOI provider.

***

**Name of repository:**
uken.rodbuk.pl

**Homepage URL of repository:**
https://uken.rodbuk.pl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
50.0738350292302, 19.90838435378484
Krakow, Poland

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
RODBUK Cracow Open Research Data Repository enables University of the National Education Commission researchers and doctoral students pursuing research projects to deposit, archive and make publicly available data from various disciplines and in various formats. Each dataset that is deposited in the repository will be automatically assigned a DOI identifier. Use of RODBUK for users is fully free of charge.

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
DOI 10.24917

**Comment by JacekChudzik** [comment]
**Name of repository:**
awf.rodbuk.pl

**Homepage URL of repository:**
https:/awf.rodbuk.pl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
50.07272997615461, 20.001238468584507
Krakow, Poland


**Year when repository started operating:**
2023

**Comment by jggautier** [comment]
These two are added to the map. Thanks @JacekChudzik!
