### ISSUE TITLE
Add my Dataverse repository: {dataportal.ing.pan.pl}

### ISSUE THREAD

**Issue by JacekChudzik** [IQSS/dataverse-installations#228]
**Name of repository:**
dataportal.ing.pan.pl

**Homepage URL of repository:**
https://dataportal.ing.pan.pl/

**Location of the repository (lat/long preferably; or street address; or city, country):**
52.22835613104999, 20.99329514038118
Warsaw, Poland

**Year when repository started operating:**
2024

**The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
IGS PAS Data Portal is an open data repository of Institute of Geological Sciences Polish Academy of Sciences. This portal is used to collect and share data, taking into account access to the data from external repositories.

IGS PAS data are open and provided for free use for non-commercial purposes under applicable laws on data sharing public and publicly funded. In the case of using data by external entities, the data source must be cited following the guidelines (information on how to cite data is included in the Cite Dataset field). 

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
10.60871

**Comment by jggautier** [comment]
dataportal.ing.pan.pl is added to the map. Thanks @JacekChudzik!
