### ISSUE TITLE
datasets.iisg.amsterdam seems to be the new datasets.socialhistory.org

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#23]
I just came across https://datasets.iisg.amsterdam at https://twitter.com/Leolucassen/status/1189871027439968256

http://datasets.socialhistory.org now redirects to https://datasets.iisg.amsterdam

Perhaps we should consider updating the hostname everywhere, in the spreadsheets, etc.

**Comment by pdurbin** [comment]
I just noticed @lwo commenting on a different issue. He has been a great contributor in the past and maybe we can get him helping with this new repo. 😄

**Comment by lwo** [comment]
Hello @pdurbin, long time. Yes, there seems to be one reference to datasets.socialhistory.org in this folder. Let me make a PR

**Comment by pdurbin** [comment]
@lwo hi! Actually, before you do, I need to ping @jggautier to update the old map. We're in transition so the process is a little confusing. Sorry! What you **can** do now is review and revise the spreadsheets mentioned in the README! 😄

**Comment by jggautier** [comment]
Okay, the URL (and version number) in the database behind the current map on dataverse.org is updated.

**Comment by pdurbin** [comment]
@jggautier thanks!

@shlake do you might updating the spreadsheets?

Then maybe @lwo can run the Python script and make a pull request?

**Comment by shlake** [comment]
@pdurbin I have updated the spreadsheets.
@lwo do you want to run the Python script and make a pull request? The instructions are in the [README file](https://github.com/IQSS/dataverse-installations/blob/master/README.md) as well as the [CONTRIBUTING file](https://github.com/IQSS/dataverse-installations/blob/master/CONTRIBUTING.md)

Let me know if the info in those two files need clarification or additions.

**Comment by pdurbin** [comment]
@lwo if you take a look at https://github.com/IQSS/dataverse-installations/blob/master/update-data.py you'll see that the way the script works is that it pulls down data from multiple sources to update `data/data.json`.

Here are the main two spreadsheets that are used but @shlake and I have a plan to move as much information as possible into the "crowdsourced" one:

- https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk/edit?usp=sharing
- https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo/edit#gid=0

Please feel free to request "edit" access to either or both spreadsheets! At minimum, it would be great to get your launch year for #7.

**Comment by lwo** [comment]
Hmm... something breaks:

```
python3 update-data.py
Traceback (most recent call last):
  File "update-data.py", line 100, in <module>
    i['country'] = mydict[i['hostname']]['country']
KeyError: 'country'

```

In my debugger it is when it reaches hostname: 'repositoriodedados.unifesp.br'
but the sheets look ok to me...

**Comment by shlake** [comment]
@lwo try now. The IQSS spreadsheet https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk/edit?usp=sharing
needs to have the country field filled in. I just did that, so it should work now.

**Comment by pdurbin** [comment]
I'm happy to jump in and troubleshoot. I wrote that hacky Python script. 😄 Lemme know!

**Comment by shlake** [comment]
@pdurbin looks like debugging in needed... but Would the fact that the IQSS sheet has 51 entries and the Harvard miniverse https://services.dataverse.harvard.edu/miniverse/map/installations-json version has 53?

The python fails on this site (in miniverse) https://repositoriodedados.unifesp.br/ which isn't in either of the crowdsource sheets

**Comment by pdurbin** [comment]
> The python fails on this site (in miniverse) https://repositoriodedados.unifesp.br/ which isn't in either of the crowdsource sheets

Good catch. Let's work on #31 to add that new installation in Brazil first and then circle back to this issue.

**Comment by shlake** [comment]
@lwo it is working now if you want to test the run/pull request.
