### ISSUE TITLE
Change data for Concorda repository

### ISSUE THREAD

**Issue by pallinger** [IQSS/dataverse-installations#232]
There are a lot of changes: name, URL, description, email, links, Handle shoulder
I will just send the whole data page again:

-------------------------

**Name of repository:**
ARP

**Homepage URL of repository:**
https://repo.researchdata.hu

**Location of the repository (lat/long preferably; or street address; or city, country):**
Budapest, Hungary
(cannot give a concrete lat/long pair, as it is multisite, but you can use SZTAKI’s coordinates as previously, if you want to: 47.47834443024498, 19.052104232575363)

**Year when repository started operating:**
2020

**A short description (few sentences) about the repository:**
The repository was originally created as Concorda, an ad-hoc initiative for data exchange during the Covid-19 pandemic by [HUN-REN Institute for Computer Science and Control](http://sztaki.hu/) (SZTAKI) and [HUN-REN Wigner Research Centre for Physics](https://wigner.hu/en) (WIGNER). Since then, the repository was significantly expanded with additional disk space and other resources donated by SZTAKI and WIGNER institutes, and accepts data from all Hungarian researchers (with some storage constraints). In 2021, the ARP project started to build research data infrastructure for the Hungarian Research Network, and chose it as the main repository component to be integrated, while also significantly expanding its storage capacity.

See also:
https://researchdata.hu/
https://fairsharing.org/4585
https://www.re3data.org/repository/r3d100014109
https://v2.sherpa.ac.uk/id/repository/10638
https://wigner.hu/
https://sztaki.hu/

**Email address of repository contact:**
support@researchdata.hu

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):**
We do not use DOI right now, we use the handle authority/shoulder "21.15109/ARP" currently, but some were issued as  "21.15109/CONCORDA".

**Comment by jggautier** [comment]
Thanks @pallinger! The repository's info is updated on the map.

<img width="388" alt="Screenshot 2024-05-28 at 12 17 08 PM" src="https://github.com/IQSS/dataverse-installations/assets/18374574/7033fb20-58bc-44c7-b9dd-8e5c650b2720">
