### ISSUE TITLE
Add my Dataverse repository:  Yale Dataverse

### ISSUE THREAD

**Issue by bseeger** [IQSS/dataverse-installations#236]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
Yale Dataverse

**Homepage URL of repository:**
https://dataverse.yale.edu

**Latitude and longitude of the repository:**

 latitude: 41.316614
longitude: -72.922209

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**

Yale Dataverse is a data repository service for Yale University faculty, staff, students, and affiliates to share, preserve, and cite research data. Yale Library hosts and manages Yale Dataverse to ensure research produced at Yale is accessible and discoverable to the global community.

**Email address of repository contact:**
 dataverseadmin@yale.edu

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map), if applicable:**
10.60600

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application, if applicable:**

**Comment by bseeger** [comment]
Hi @shlake - thank you so much for adding us! I thought I had a few additional steps to go through (updating the spreadsheet and pushing a PR myself as described in the contributing md file) so I didn't include all the information.   Could you please add our about url?   (unless it's not used or necessary?)

* about_url: https://researchdata.yale.edu/yale-dataverse

Thanks so much!

**Comment by shlake** [comment]
Hi @bseeger I have added Yale's About info. It shows up when you click your "dot" on the pop-up "More" link at the end of the description.
