### ISSUE TITLE
Installation list cut off in Dataverse.org

### ISSUE THREAD

**Issue by bseeger** [IQSS/dataverse-installations#239]
Hello, 

On the https://dataverse.org/installations page the listing containing all the installations is cut off in the middle of a description.   

Opening the map in a new window works fine and shows the full listing. 

In both places all the installs do show up on the map, so it seems. 

I'm pretty sure this isn't the correct place to report this issue, as it's probably something in the Dataverse.org setup, but I wasn't sure where to mention this. 

Thanks,
Bethany

**Comment by pdurbin** [comment]
Hmm, yeah, it looks like it's cut off around the R's:

![Screenshot 2024-07-24 at 12 13 23 PM](https://github.com/user-attachments/assets/06dfc530-cf76-4744-a616-49dd2c404337)

**Comment by pdurbin** [comment]
The height was 8000...

![Screenshot 2024-07-24 at 12 15 34 PM](https://github.com/user-attachments/assets/c631fda3-8689-4b3e-a220-0ffa284b7a0f)

... and I just doubled it.

@bseeger it might take a few minutes for the change to show up. Thanks for reporting this bug!

**Comment by bseeger** [comment]
Great! I was wondering if there was some sort of limit in place, as the text itself looked fine (with no strange characters that could cause issue). 

Thanks for fixing it @pdurbin!

**Comment by bseeger** [comment]
I will note that now there's a lot of empty space there, but I can imagine this will be tricky unless it's spaced dynamically.

**Comment by pdurbin** [comment]
Yeah, I'm afraid it isn't spaced dynamically. This way, we have some room to grow. 😄
