### ISSUE TITLE
Removing University of Manitoba Dataverse from known installations list and map

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#243]
University of Manitoba Dataverse has migrated to Borealis and the hostname we have, http://dataverse.lib.umanitoba.ca, redirects to a collection in Borealis. I'm going to remove University of Manitoba Dataverse from the list of known Dataverse installations and from the map.

**Comment by pdurbin** [comment]
😢

**Comment by jggautier** [comment]
Maybe this is another argument for somehow exposing different types of organizations that are using a single Dataverse installation? I looked for a GitHub issue about that idea; I know it's been brought up by others, though I couldn't find one discussion about it in the issues in this dataverse-installations repo.

**Comment by pdurbin** [comment]
Same, I can't find an issue here but it's definitely been discussed! The old map even had small grey circles but the only represented collections from one installation (Harvard's). We want to implement something for the whole community.
