### ISSUE TITLE
Add my Dataverse repository: Repositorio de datos de Investigación UdeA

### ISSUE THREAD

**Issue by laureanofg** [IQSS/dataverse-installations#246]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
[Repositorio de datos de Investigación UdeA](https://datosdeinvestigacion.udea.edu.co/dataverse/UDEA)

**Homepage URL of repository:**
https://datosdeinvestigacion.udea.edu.co/

**Latitude and longitude of the repository:**
Medellín, Colombia
Latitude | 6.230833
longitude  -75.590553

**Year when repository started operating:**
2024-10-01

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
The Research Data Management System (GDI) is a service provided by the Library System and the Vice-Rectorate for Research of the University of Antioquia, designed specifically for researchers and operated online through the Dataverse platform. Its main function is to manage the collection of open data produced by the University in the course of teaching, research and extension activities.

**Email address of repository contact:**
repositoriodedatos@udea.edu.co

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map), if applicable:**
10.60905

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application, if applicable:**

**Comment by jggautier** [comment]
Hi @laureanofg. Thanks for letting us know about Repositorio de datos de Investigación UdeA. I'll add it to the Dataverse map at https://dataverse.org today!

**Comment by jggautier** [comment]
It's added! Thanks again!
