### ISSUE TITLE
Add my Dataverse repository: DeiC Dataverse

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#248]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
DeiC Dataverse

**Homepage URL of repository:**
https://dataverse.deic.dk

**Latitude and longitude of the repository:**
55.68061837049594, 12.572245878215593

**Year when repository started operating:**
2024

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
DeiC Dataverse is the Danish National Repository for Research Data and is available to all universities in Denmark. It is operated by the Danish e-infrastructure Consortium, DeiC, in collaboration with the University of Copenhagen.

**Email address of repository contact:**
sekretariat@deic.dk

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map), if applicable:**
10.60612

**Comment by jggautier** [comment]
I'm emailing with Falco (in the email thread at https://help.hmdc.harvard.edu/Ticket/Display.html?id=370480) to make sure this information is correct before using it to add the new repository to the Dataverse map.

**Comment by Falco-KUB** [comment]
Thank you very much for your help @jggautier 
I hadn't realized earlier that I just could have created the ticket myself...

**Description**
DeiC Dataverse is the Danish National Repository for Research Data and is available to all universities in Denmark. It is operated by the Danish e-infrastructure Consortium, DeiC, in collaboration with the University of Copenhagen.

**DOI authority:**
10.60612

**Comment by jggautier** [comment]
DeiC Dataverse is added! 🎉

**Comment by Falco-KUB** [comment]
Thank you very much.
Philip Durbin had provided me with the link in Zulip:
[https://dataverse.zulipchat.com/#narrow/stream/375707-community/topic/DeiC.20Dataverse.20is.20live](https://dataverse.zulipchat.com/#narrow/stream/375707-community/topic/DeiC.20Dataverse.20is.20live)

**Comment by jggautier** [comment]
Ah interesting, thanks. And Phil probably knew you'd be fine with creating a GitHub issue. But I'd already started working on this after seeing your email.

Luckily, I think, we're not adding so many installations that we need to be more efficient about it!

**Comment by Falco-KUB** [comment]
Oh, I can see that the link to the repository has been cut off on the map - it should be https://dataverse.deic.dk/
(now it only says 'deic'dk')
