### ISSUE TITLE
Add my Dataverse repository: ULiège Open Data Repository

### ISSUE THREAD

**Issue by jbiernaux** [IQSS/dataverse-installations#250]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
ULiège Open Data Repository

**Homepage URL of repository:**
https://dataverse.uliege.be/

**Latitude and longitude of the repository:**
50°38'27.7"N 5°34'32.5"E

**Year when repository started operating:**
2023

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
The ULiège Dataverse is the ULiège institutional open data sharing repository, used by ULiège researchers to share datasets with the global scientific community, according to the FAIR data principles. 

**Email address of repository contact:**
dataverse.admin@uliege.be

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map), if applicable:**
10.58119

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application, if applicable:**

**Comment by jggautier** [comment]
Thanks @jbiernaux! ULiège Open Data Repository should appear on the Dataverse map in a few minutes 🎉
