### ISSUE TITLE
Add Core Trust Seal to Borealis for University of Victoria Dataverse

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#251]
As announced by @amberleahey at https://groups.google.com/g/dataverse-community/c/po26Isl2l2g/m/bzW_7wcXAgAJ [University of Victoria Dataverse](https://borealisdata.ca/dataverse/uvic) has been certified as a Trustworthy Data Repository by the [CoreTrustSeal](https://amt.coretrustseal.org/certificates) Standards and Certification Board! 🎉 

We should add the CoreTrustSeal to the map!

Judging from https://amt.coretrustseal.org/certificates we don't have to link to PDFs anymore. We can link to DOIs.

https://doi.org/10.34894/PUHYXX seems to be the one for UVic, listed at https://amt.coretrustseal.org/certificates

In the [spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo/edit?usp=sharing), the column to use is core_trust_seals (yes, plural, it's comma separated).

**Comment by shlake** [comment]
@pdurbin do we add this to Borealis' line in the crowdsourced doc.... or do we create a new one for University of Victoria?

This is what you were talking about... adding a thread to Zulip to discuss?

**Comment by pdurbin** [comment]
@shlake please add it to the row for Borealis. And yes, I'm happy to discuss here or Zulip or wherever. 😄

**Comment by pdurbin** [comment]
Looking good! Thanks, @shlake! 

![Screenshot 2024-10-29 at 11 40 44 AM](https://github.com/user-attachments/assets/cdf68a6c-f7ca-4972-88b2-e352a7d529d5)
