### ISSUE TITLE
Add my Dataverse repository: UCLA Dataverse  - need to add description

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse-installations#255]
*All information shared will be publicly available. It will also be displayed on the map unless otherwise indicated*

**Name of repository:**
UCLA Dataverse

**Homepage URL of repository:**
https://dataverse.ucla.edu/

**Latitude and longitude of the repository:**
34.0699° N, 118.4438° W  (UCLA campus)

**Year when repository started operating:**
2019

*The following isn't required but is nice to have:*
[Global Dataverse Community Consortium](http://dataversecommunity.global/) member
Included in [dataverse.org/metrics](https://dataverse.org/metrics)

**A short description (few sentences) about the repository:**
UCLA Dataverse allows for the sharing and storage of data from UCLA research. This makes it accessible, discoverable and reusable by the public. The platform also hosts sub-dataverses for different campus groups like schools or departments.

**Email address of repository contact:**

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map), if applicable:**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application, if applicable:**

**Comment by shlake** [comment]
Closed with PR #256
