### ISSUE TITLE
Add datarepositorium.sdum.uminho.pt to the map

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#28]
https://datarepositorium.sdum.uminho.pt was just added to the old map, bringing the total number of installations to 51.

**Comment by shlake** [comment]
@pdurbin to add this to the new map, I need to add an entry for it on the "IQSS maintained" spreadsheet right? It's not there.

No problem in me adding it, just want to make sure that has to be done manually, vs waiting for something from the old map.

**Comment by pdurbin** [comment]
@shlake right, I believe it needs to be added to both spreadsheets. We should document the process. I'll go ahead and assign this to you but if you want me to give you a ring and walk though it, please let me know!

**Comment by shlake** [comment]
Datarepositorium is on the map!

**Comment by pdurbin** [comment]
@shlake looks great! Thanks!!! 🎉 🎉 🎉 

![Screen Shot 2019-11-14 at 11 03 12 AM](https://user-images.githubusercontent.com/21006/68873948-68d46100-06ce-11ea-9bbd-561a197892f4.png)
