### ISSUE TITLE
Add dataverse.arch.be to the map

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#30]
https://dataverse.arch.be should be added to the new map once it has been added to the old map: https://help.hmdc.harvard.edu/Ticket/Display.html?id=283158

See also discussion at http://irclog.iq.harvard.edu/dataverse/2019-11-14#i_112429

**Comment by pdurbin** [comment]
https://dataverse.arch.be is technically already on the map at https://iqss.github.io/dataverse-installations/ already now that pull request #32 has been merged:

![Screen Shot 2019-11-20 at 4 20 21 PM](https://user-images.githubusercontent.com/21006/69279180-d3473e80-0bb1-11ea-9a82-824e163a173a.png)

This puts the new map one installation head of the old map.

The reason for this is that the Python script pays no attention to "is_active" in the JSON that powers the old map: https://services.dataverse.harvard.edu/miniverse/map/installations-json

![Screen Shot 2019-11-20 at 4 19 21 PM](https://user-images.githubusercontent.com/21006/69279241-efe37680-0bb1-11ea-9fae-9a369ab9b29d.png)

Hopefully @youssefOuahalou and @jggautier don't mind. 😄

**Comment by shlake** [comment]
But it's not in our crowdsourced sheets.

I was going to add it to our sheets and then close this.

**Comment by pdurbin** [comment]
@shlake yes, you're absolutely right. That's fine with me too. I'm just saying that the new map will be ahead of the old map for a bit. I'm fine with that too. Eventually we want to retire the old map. That's what https://github.com/IQSS/dataverse.org/issues/66 is about. 😄

**Comment by jggautier** [comment]
@youssefOuahalou and I agreed it wouldn't be added to the map until we heard back from them, so I entered the information and marked it as inactive for now.

**Comment by pdurbin** [comment]
@jggautier thanks. It sounds like for this repo we should either:

- honor "false" for "is_active" for the old map
- implement some sort of skip list for installation that want to start entering data in the old map or the new spreadsheets but don't want to be shown on the map yet

Again, the first idea above would be probably a temporary measure until we move off the old map as part of https://github.com/IQSS/dataverse.org/issues/66

**Comment by youssefOuahalou** [comment]
thank you very much to all :1st_place_medal: (:

**Comment by pdurbin** [comment]
> honor "false" for "is_active" for the old map

I just made pull request #36 to start respecting "is_active".

**Comment by shlake** [comment]
@pdurbin so this can be closed since it will appear on this new map when  "is_active" = TRUE?

**Comment by pdurbin** [comment]
@shlake well, the current problem is that https://dataverse.arch.be is already on the new map. Now that you merged pull request #36 we should be able to run the python script to remove this installation from the new map until "is_active" becomes true.

I'll go make a pull request for this. 😄
