### ISSUE TITLE
Update information on the map for DataverseNL

### ISSUE THREAD

**Issue by LauraHuisintveld** [IQSS/dataverse-installations#33]
I have three changes for DataverseNL on the map. 
1. The harvesting set should be 'uvt_datasets' instead of 'tilburg_oai'. 
2. I changed the description in the spreadsheet into: 'DataverseNL is a data repository hosted by DANS. Researchers associated with the DataverseNL partners (Several universities, higher education and research institutes) are able to deposit data. '
3. Our location coordinates should be: latitude 52.0808304 longitude, 4.3456727

**Comment by pdurbin** [comment]
@LauraHuisintveld thanks for opening this issue!

@jggautier can you please update the lat/long? (Or teach me how to do it.)

Once all the changes are in place we could see if @LauraHuisintveld is interested in running the Python script and making a pull request. :smile:

**Comment by jggautier** [comment]
Made PR #34 for these changes.

**Comment by pdurbin** [comment]
> Once all the changes are in place we could see if @LauraHuisintveld is interested in running the Python script and making a pull request. 😄

@LauraHuisintveld sorry, we went ahead without you. Now that pull request #34 has been made, here's how the map looks:

![Screen Shot 2019-12-05 at 12 23 22 PM](https://user-images.githubusercontent.com/21006/70258379-2694c180-175a-11ea-8a18-680a108493d4.png)

If you want to make a pull request in the future, please just let us know! I just coached @jggautier through the process and he made it look easy. 😄
