### ISSUE TITLE
add uclouvain site

### ISSUE THREAD

**Issue by ppdaz26** [IQSS/dataverse-installations#49]
Hi,
Could you add our dataverse installation for "Université catholique de Louvain" - UCLouvain ?

Regards,

Patrick

Installation hostname: dataverse.uclouvain.be
Builtin login : yes
Shibboleth login: yes
Country : Belgium
Continent: Europe
DOI authority: 10.14428
GDCC member: no

**Comment by jggautier** [comment]
The logo (below), Dataverse version version, and lat/long have been added to miniverse

![UCLouvain-46x46](https://user-images.githubusercontent.com/18374574/73279255-d9adf400-41ba-11ea-8401-b6fdc18e451a.png)

**Comment by pdurbin** [comment]
Since #42 is already in the sprint I suppose we should add work on this one at the same time.
