### ISSUE TITLE
Duplicate Institutions in Crowdsourced file

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse-installations#52]
This site: https://repositoriodedados.unifesp.br/
has two entries in crowdsourced spreadsheet: https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo/edit#gid=0

Each with different descriptions and launch year.

Need to resolve.

**Comment by jggautier** [comment]
I removed the row with the entry that was marked as skipped.
