### ISSUE TITLE
Add Jülich DATA to the map

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-installations#55]
We're getting there... Being no. 55 :smile: 

I already added us to https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo

How shall I add the other data? The contribution guide didn't enlighten me much :neutral_face:

**Comment by pdurbin** [comment]
Hooray! 🎉 

The first step is to add it to https://services.dataverse.harvard.edu/miniverse/map/installations-json (the old map) which is being tracked in https://help.hmdc.harvard.edu/Ticket/Display.html?id=286824 (the ticket you opened, thanks!).

@poikilotherm can you please go ahead and request edit access to https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk/edit?usp=sharing ?

**Comment by poikilotherm** [comment]
Both done. :smile:

**Comment by pdurbin** [comment]
@poikilotherm cool. While we wait for the old map to get updated, do you feel like running `python3 update-data.py` to make a pull request to pick up some unrelated changes?

**Comment by jggautier** [comment]
The database behind the old map is updated with info about Jülich DATA (lat/long, logo, etc)

**Comment by pdurbin** [comment]
@jggautier thanks! It's weird, I see it in the old map at https://services.dataverse.harvard.edu/miniverse/map/ but not in the JSON output:

`$ curl -s https://services.dataverse.harvard.edu/miniverse/map/installations-json | jq . | fgrep .de`

```
      "url": "https://darus.uni-stuttgart.de/",
      "url": "https://data.gro.uni-goettingen.de/",
      "url": "https://heidata.uni-heidelberg.de/",
```

**Comment by pdurbin** [comment]
@jggautier please disregard last comment. Jülich DATA is now in https://services.dataverse.harvard.edu/miniverse/map/installations-json

@poikilotherm this means you can go ahead and make a pull request if you'd like. 😄 

After running `python3 update-data.py` that is. 😄

**Comment by poikilotherm** [comment]
@jggautier could you do me the favor to rename us from "Jülich Data Installation" to "Jülich DATA"? 
I also would like to change that logo - should I send you a pic as an answer to the ticket email?

Thank you very much!

**Comment by jggautier** [comment]
Sure. I just changed the name in the old map's database.

Feel free to send the logo as a comment in this GitHub issue or in that ticket email. Preferably a square logo, since all of the other logos are squared. Thanks!

**Comment by poikilotherm** [comment]
I already deleted the RT mails... Here you go: https://fz-juelich.sciebo.de/s/UQqItfWyUwBtjsP

**Comment by jggautier** [comment]
Okay, I changed the logo.

Maybe there's a delay with that JSON file getting updated?

**Comment by poikilotherm** [comment]
OK, let me just push you hand-edited changes. Should be patrolled to generate the same result...

**Comment by pdurbin** [comment]
@poikilotherm for "description" the crowdsourced spreadsheet "wins" over what's in the old map JSON: https://github.com/IQSS/dataverse-installations/blob/430ef6f14786038b66d0f1333a68d2ca215973f0/update-data.py#L25-L29

It overwrites "description", I mean, when producing data.json.

If you'd like to add a new column in that spreadsheet for "name" and similar logic in the script above, please go ahead and make a pull request (and an issue, if you feel like it).
