### ISSUE TITLE
give attribution to OpenStreetMap

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#57]
Via https://twitter.com/MapperFr/status/1233013524508676096 we need to look into https://www.openstreetmap.org/copyright/ and figure out what to give attribution to @openstreetmap for their awesome map tiles! This is totally my fault. I was hacking, hacking, hacking early on and probably accidentally removed it. Sorry! We'll fix it.

![Screen Shot 2020-02-27 at 10 53 37 AM](https://user-images.githubusercontent.com/21006/75460403-6c26ec00-594f-11ea-83d3-9d4a129e676c.png)

**Comment by mheppler** [comment]
Copyright added in #58.

![Screen Shot 2020-02-27 at 12 03 11 PM](https://user-images.githubusercontent.com/687227/75467317-777f1500-5959-11ea-8d81-b5dd3c39a085.png)
