### ISSUE TITLE
Plans for repository logos

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#61]
Should we continue collecting logos for each repository added to the new Dataverse map? They're in the old database and in a Google drive folder, but not being used by the new map or table.

**Comment by jggautier** [comment]
Closing this issue.

**Comment by TaniaSchlatter** [comment]
I think we should keep collecting them, @jggautier. Even though we are not using them now, it would be great to have them for future use.

**Comment by jggautier** [comment]
Could we collect them when we need them? There's also the good chance some logos will have changed by the time we want to use them, depending on when we think we'll use them.

**Comment by TaniaSchlatter** [comment]
That's possible, but it makes it hard to plan to use something we don't have. I agree logos might change. I don't know how much work it is to get them, so I'll leave it up to you.
