### ISSUE TITLE
Add CoreTrustSeal to DataverseNO record on global Dataverse map

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse-installations#62]
Please add information about CoreTrustSeal to the DataverseNO record on the global Dataverse map (see [discussion](https://groups.google.com/forum/?hl=no#!topic/dataverse-community/yxqAN1lH6Jc) in Google Group).

https://www.coretrustseal.org/wp-content/uploads/2020/03/DataverseNO.pdf

Thanks!

Maybe this information could be pulled directly from [re3data](https://www.re3data.org/)?

**Comment by pdurbin** [comment]
@philippconzett thanks for creating this issue!

The first step is to update the "CoreTrustSeals" column in this spreadsheet (please feel free to request edit access): https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk/edit?usp=sharing

Here's how it looks:

<img width="1312" alt="Screen Shot 2020-04-08 at 10 59 49 AM" src="https://user-images.githubusercontent.com/21006/78799499-36cae080-7988-11ea-8960-87bad039acc5.png">

Then someone needs to run the `update-data.py` script and make a pull request.

I'm happy to mentor.

**Comment by shlake** [comment]
@pdurbin I will update the spreadsheet and run the script.
Question: what goes in the column? yes/no or something else?

**Comment by pdurbin** [comment]
@shlake thanks!

https://www.coretrustseal.org/wp-content/uploads/2020/03/DataverseNO.pdf should go in the column.

I have logic to the column could have multiple URLs separated by commas but we don't have any cases of multiple CoreTrustSeal URLs for a single installation of Dataverse. But maybe DataverseNL will get a second one? After Tilburg.

**Comment by shlake** [comment]
@pdurbin I just updated the data.json file to add CoreTrust seal to this map. Is this considered the "global Dataverse map", or is the map on dataverse.org the "global" one?

If this update on data.json closes this issue, this please close, or let me know & I will.

**Comment by pdurbin** [comment]
@shlake this pull request was perfect! Thanks!

Yes, the map in this repo is considered the global Dataverse map. The old map still exists (and we use its JSON as a data source for now) but we don't link to it anymore. So I'll close this issue. Thanks again! 🎉 

For @philippconzett and others who are curious, here's how the CoreTrustSeal certification looks in the popup (note that if you hover and click, you get a PDF of the CoreTrustSeal details):

<img width="1214" alt="Screen Shot 2020-04-14 at 10 46 18 AM" src="https://user-images.githubusercontent.com/21006/79238572-8b190900-7e3d-11ea-8625-ee8d8817dbed.png">

Congrats again to all the Dataverse installations that have earned the CoreTrustSeal certification! 💯 🎉

**Comment by philippconzett** [comment]
> @shlake thanks!
> 
> https://www.coretrustseal.org/wp-content/uploads/2020/03/DataverseNO.pdf should go in the column.
> 
> I have logic to the column could have multiple URLs separated by commas but we don't have any cases of multiple CoreTrustSeal URLs for a single installation of Dataverse. But maybe DataverseNL will get a second one? After Tilburg.

Adding a CoreTrustSeal to DataverseNL on the map may lead to some confusion, as DataverseNL actually is not CoreTrustSeal certified, only one of the repositories within DataverseNL (=Tilburg Dataverse). DataverseNL is a technical infrastructure provider, not a repository, whereas Tilburg Dataverse is a repository. Both types of infrastructures can be certified, but the certification would ask for quite different evidence for these two types. For DataverseNO, we decided to design it as ONE repository with institutional collections, and we certified the entire DataverseNO. This made certification much more demanding, but in the end we succeeded.

**Comment by pdurbin** [comment]
@philippconzett well, I hope it helps that I made the CoreTrustSeal icon a link so you can click it and go to https://www.coretrustseal.org/wp-content/uploads/2018/04/Tilburg-University-Dataverse.pdf to get details about Tilburg rather than DataverseNL.
