### ISSUE TITLE
Two URLs same Site - Which to use?

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse-installations#64]
@jggautier I updated this dataverse-installation map, but found out that _data.inra.fr_ and _data.inrae.fr_ both seem to appear in the miniverse version? but only _data.inra.fr_ appears in the spreadsheets used here. 
The update program gave a warning: `On old map only: data.inrae.fr`

**Comment by jggautier** [comment]
An admin of Data Inrae asked in https://github.com/IQSS/dataverse-metrics/pull/41#issue-394819187 that the URL to their repository be changed to https://data.inrae.fr

From what I can tell, that's what's in the miniverse database:

<img width="816" alt="Screen Shot 2020-04-14 at 2 16 53 PM" src="https://user-images.githubusercontent.com/18374574/79259370-9c244300-7e5a-11ea-9cd0-85a0599d54cc.png">

It looks like the [two](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo/edit#gid=0) [spreadsheets](https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk/edit#gid=639378778) have the old URL and they should be updated.

**Comment by shlake** [comment]
@jggautier actually, both spreadsheets had the new URL - data.inrae.fr, but I got an error when I tried to run the update here (error was w/ data.inra.fr?). I couldn't figure where it came from, so I changed the spreadsheet to data.inra.fr and it worked.

I'll try again tomorrow (updating the spreadsheets to the correct URL) and see what happens.

**Comment by jggautier** [comment]
Ah, okay. I'll stand by then.
