### ISSUE TITLE
CoreTrustSeal for dataverse.ada.edu.au

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#65]
@janetm recently mentioned that https://dataverse.ada.edu.au has the CoreTrustSeal certification! See https://groups.google.com/d/msg/dataverse-community/yxqAN1lH6Jc/xzo4HnueBwAJ

We should add it, just like we did for DataverseNO in #62.

I found https://www.coretrustseal.org/wp-content/uploads/2018/02/Australian-Data-Archive.pdf at https://www.coretrustseal.org/why-certification/certified-repositories/

<img width="1552" alt="Screen Shot 2020-04-14 at 3 42 59 PM" src="https://user-images.githubusercontent.com/21006/79267198-c11eb300-7e66-11ea-8ed0-ba9911bec985.png">

**Comment by shlake** [comment]
Added to spreadsheet maintained by IQSS: 
https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk

**Comment by pdurbin** [comment]
Added in 76ad6ac.

<img width="403" alt="Screen Shot 2020-05-07 at 1 19 49 PM" src="https://user-images.githubusercontent.com/21006/81324774-72c79300-9065-11ea-8e87-47f8754d2a3a.png">

Congrats @janetm et al.!
