### ISSUE TITLE
Add Yale-NUS Dataverse to the Dataverse map

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#66]
I asked the repository admin to include in the crowdsourced spreadsheet a brief description of the repository. Waiting to hear back.

- [x] Repository admin provided brief description in the [crowdsourced spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo)
- [x] Repository added to miniverse database
- [ ] Script for updating JSON file was run

**Comment by jggautier** [comment]
Blocked by update script throwing an error. See https://github.com/IQSS/dataverse-installations/issues/68

**Comment by pdurbin** [comment]
Added in 6b35b03.
