### ISSUE TITLE
Why doesn't Yale-NUS Dataverse's link on the map use https?

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#73]
On the map, the link for Yale-NUS Dataverse goes to http://dataverse.yale-nus.edu.sg, which does not go to the installation's site. Adding https, https://dataverse.yale-nus.edu.sg, takes you to the site.

When I click on other installation links on the map, the URL changes to use https, even though the crowdsourced spreadsheet (and the data.json file) don't specify https.

When I add https to Yale-NUS's URL in the spreadsheet, run the update script, and look at the map locally, the URL is missing the colon, i.e https//dataverse.yale-nus.edu.sg

**Comment by pdurbin** [comment]
@jggautier here's where you can see that plain "http://" is added to the hostname:

https://github.com/IQSS/dataverse-installations/blob/8d4924de04132c9f3e1fc9d21fc537403a910aa2/js/map.js#L63-L64

We should contact this installation and point out that the plain http version doesn't redirect to the https version. Redirects like this are extremely common. We document how to set up a redirect using Apache at http://guides.dataverse.org/en/4.20/installation/shibboleth.html#enforce-https

**Comment by jggautier** [comment]
Sounds good. Thanks for contacting them. Closing this issue.
