### ISSUE TITLE
Add my Dataverse repository: ICRAF

### ISSUE THREAD

**Issue by alejandratenorio** [IQSS/dataverse-installations#75]
**Name of repository:** World Agroforestry - Research Data Repository	

**Homepage URL of repository:** https://data.worldagroforestry.org/

**A few sentences about the repository:**

**Location of the repository (street address if possible):** United Nations Avenue, Gigiri
PO Box 30677, Nairobi, 00100, Kenya

*The following isn't required but is nice to have:*
Email address of repository contact: a.tenorio@cgiar.org

Year when repository opened: 2019

DOI authority (if applicable): 10.34725

Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:

**Comment by shlake** [comment]
@pdurbin Added to Crowsdsourced sheet, now do I run the update script?

**Comment by pdurbin** [comment]
@shlake yes! Please let me know if you have any trouble! I rewrote it recently. Should work. 😄

**Comment by shlake** [comment]
World Agroforestry - Research Data Repository: added to Dataverse installations map
