### ISSUE TITLE
Add my Dataverse repository: {Repositório Institucional de Dados para Pesquisa da Fiocruz}

### ISSUE THREAD

**Issue by Fiocruz-RIDP** [IQSS/dataverse-installations#82]
**Repositório Institucional de Dados para Pesquisa da Fiocruz:**

**https://dadosdepesquisa.fiocruz.br/dataverse.xhtml:**

**Rio de Janeiro:**

*The following isn't required but is nice to have:*

**The institutional research data repository for Oswaldo Cruz Foundation (Fiocruz). Fiocruz researchers are encouraged to use the data repository to deposit, publish and archive their research data in order to make their research data findable, accessible and reusable.:**

**dadosabertos@fiocruz.br:**

**2020:**

**10.35078:**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by Fiocruz-RIDP** [comment]
Fiocruz's address is: Av. Brasil, 4365 - Manguinhos, Rio de Janeiro - RJ

**Comment by jggautier** [comment]
Thanks @Fiocruz-RIDP. I've added this info to the spreadsheet at https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo, which is the source of the data for the map on dataverse.org. But a marker for the repository won't show up on the map until you let me know you would like it to.

(I asked in an email exchange with Vanessa de Arruda Jorge today if the repository should show right away or if we should wait.)

**Comment by Fiocruz-RIDP** [comment]
> Thanks @Fiocruz-RIDP. I've added this info to the spreadsheet at https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo, which is the source of the data for the map on dataverse.org. But a marker for the repository won't show up on the map until you let me know you would like it to.
> 
> (I asked in an email exchange with Vanessa de Arruda Jorge today if the repository should show right away or if we should wait.)

Thanks @jggautier ! The map can show the repository right away. It is already working. We will publish datasets soon. Thanks again

**Comment by vanessaajorge** [comment]
Hi @jggautier ! Do we have to complete any data in the spreadsheet? Thanks!

**Comment by jggautier** [comment]
Hi @vanessaajorge. I see that some [more info was added](https://github.com/IQSS/dataverse-installations/issues/82#issue-702955980) (a description of the repository and the DOI authority), so I'll add those to the spreadsheet and update the map.

If there are any other columns of [the spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo) that you'd like to fill out, please let me know.
