### ISSUE TITLE
Add my Dataverse repository: ASU Library Research Data Repository

### ISSUE THREAD

**Issue by nightowlaz** [IQSS/dataverse-installations#83]
**Name of repository:**
ASU Library Research Data Repository

**Homepage URL of repository:**
https://dataverse.asu.edu

**Location of the repository (city or street address if possible):**
Tempe,  Arizona

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
ASU Library's research data repository (powered by Harvard’s Dataverse software) helps ASU affiliated researchers share, store, preserve, cite, explore, and make research data accessible and discoverable. Dataverse is a dedicated research data management service platform that serves in the publication and reuse phase of the research data lifecycle and works in concert with the ASU Digital Repository ecosystem to present a more complete picture of ASU’s scholarly activities.

**Email address of repository contact:**
researchsupport@asu.edu

**Year when repository started operating:**
2020

**DOI authority (if applicable):**
DataCite

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**
We are working on this, but haven't applied yet.

**Comment by shlake** [comment]
@jggautier What steps do you do to get this on the map? Are there still two places (three) with "sources" of data for the map?

**Comment by jggautier** [comment]
Hi @shlake. @pdurbin moved all of the info to [one Google Sheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo/edit#gid=0), so we just add a new row to the spreadsheet, run the update script and make a pull request. Hopefully that's all clear from the [contributing guide](https://github.com/IQSS/dataverse-installations/blob/master/CONTRIBUTING.md)

**Comment by shlake** [comment]
I thought there was another file that you @jggautier had to update? Or is everything now coming from that Google Sheet? It's been awhile and I am rusty (obviously).😉

**Comment by jggautier** [comment]
Everything's coming from the Google Sheet now. The lat/long was pulled from a separate database, but that's been moved to and is being pulled from the Google Sheet now, too.

**Comment by jggautier** [comment]
@nightowlaz, I updated the spreadsheet to indicate that ASU is a GDCC member. It's on the map now.

**Comment by nightowlaz** [comment]
Thank you!

Deirdre Kirmis
Technology Services
Arizona State University Library
480-965-7240

**Comment by pdurbin** [comment]
@jggautier it sounds like we should let @shlake do the next one. 😄 

Welcome aboard, @nightowlaz! 🎉
