### ISSUE TITLE
Add my Dataverse repository: Repositorio de datos de investigación de la Universidad de Chile

### ISSUE THREAD

**Issue by rafael-castillo** [IQSS/dataverse-installations#84]
**Name of repository:**
Repositorio de datos de investigación de la Universidad de Chile

**Homepage URL of repository:**
https://datos.uchile.cl/

**Location of the repository (city or street address if possible):**
Santiago de Chile. Diagonal Paraguay 265. Región Metropolitan

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
El Repositorio de datos de investigación de la Universidad de Chile conserva, difunde y proporciona acceso a los datos de investigación generadas por sus académicos e investigadores, con el fin de dar visibilidad a dichos datos, garantizar su preservación y facilitar su acceso y reutilización.

**Email address of repository contact:**
sisib@uchile.cl

**Year when repository started operating:**
2019

**DOI authority (if applicable):**
DATACITE

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
@shlake, did you want to add one? It's the first known one in Chile!

**Comment by shlake** [comment]
@jggautier Sure, I'll add, get me back in practice.

**Comment by shlake** [comment]
Closed with pull request #85

**Comment by pdurbin** [comment]
@rafael-castillo welcome to the Dataverse community!

@shlake thanks for adding Universidad de Chile to the map! Like @jggautier said, it's the first in Chile. Here's the screenshot I just shared in Slack:

<img width="411" alt="Screen Shot 2020-10-21 at 10 08 46 AM" src="https://user-images.githubusercontent.com/21006/96732096-f95afd00-1385-11eb-9bf9-785a73589dc1.png">
