### ISSUE TITLE
Add my Dataverse repository: Datos

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-installations#88]
**Name of repository:**
Datos

**Homepage URL of repository:**
datos.cedia.edu.ec

**Location of the repository (city or street address if possible):**
Lat: -2.90791 Long: -79.01080 (Gonzalo Cordero Dávila & J. Fajardo, Cuenca, Ecuador)

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
CEDIA's Research Data Repository preserves, disseminates and gives access to research data generated by its academics and researchers, in order to give visibility, guarantee its conservation and facilitate its access and reuse. Researchers, journals, data authors, publishers, data distributors, and affiliated institutions receive academic credit and visibility on the web.

**Email address of repository contact:**
freddy.sumba@cedia.org.ec, neg@cedia.org.ec

**Year when repository started operating:**
2020

**DOI authority (if applicable):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
@shlake or @pdurbin, would you like to do the honors? If not, I can. ツ

**Comment by pdurbin** [comment]
@jggautier you know, it's been a while. I'll get this one.

**Comment by shlake** [comment]
@pdurbin Thanks. I'm still in a workshop & wouldn't be able to get it until later this afternoon.

**Comment by pdurbin** [comment]
>  [freddy.sumba@cedia.org.ec](mailto:freddy.sumba@cedia.org.ec), [neg@cedia.org.ec](mailto:neg@cedia.org.ec)

I don't like how this looks (should be a single address)...

"contact_email": "freddy.sumba@cedia.org.ec, neg@cedia.org.ec"

... so I'm going with the single generic non-person address instead, like this:

"contact_email": "neg@cedia.org.ec"

I the future, perhaps we could express multiple email addresses in an array.

**Comment by pdurbin** [comment]
Ok. Add in pull request #89. First installation in Ecuador! Here it is on the map:

<img width="374" alt="Screen Shot 2020-12-01 at 2 54 29 PM" src="https://user-images.githubusercontent.com/21006/100790003-3b477c00-33e5-11eb-85e4-7504f161a803.png">
