### ISSUE TITLE
Add my Dataverse repository: Florida International University Research Data Portal

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse-installations#91]
**Name of repository:**

Florida International University Research Data Portal

**Homepage URL of repository:**

https://dataverse.fiu.edu/

**Location of the repository (city or street address if possible):**

11200 SW 8th St, Miami, FL 33199

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**

The FIU Research Data Portal serves as an inter-disciplinary data archive to support access and reuse of research data produced at FIU.

**Email address of repository contact:**

rdm@fiu.edu

**Year when repository started operating:**

2020

**DOI authority (if applicable):**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by shlake** [comment]
@shlake here, I can do this Wed morning.

**Comment by shlake** [comment]
Updated Crowdsourced Spreadsheet

**Comment by shlake** [comment]
Closed w/ #92

**Comment by djbrooke** [comment]
Thanks @shlake !!
