### ISSUE TITLE
Add my Dataverse repository: Open Forest Data

### ISSUE THREAD

**Issue by MRIPAS** [IQSS/dataverse-installations#94]
**Name of repository:** Open Forest Data

**Homepage URL of repository:** https://dataverse.openforestdata.pl/

**Location of the repository (city or street address if possible):** Białowieża, Poland

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:** Podlasie digital repository of natural science data

**Email address of repository contact:** jlapinska@ibs.bialowieza.pl

**Year when repository started operating:** 2020

**DOI authority (if applicable):** DataCite

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by pdurbin** [comment]
@shlake looks great! Thanks!

<img width="465" alt="Screen Shot 2021-01-05 at 2 04 30 PM" src="https://user-images.githubusercontent.com/21006/103687879-fae89a00-4f5e-11eb-92d3-341bc554c29e.png">
