### ISSUE TITLE
Add my Dataverse repository: CROSSDA

### ISSUE THREAD

**Issue by mglavica** [IQSS/dataverse-installations#96]
**Name of repository:**
CROSSDA

**Homepage URL of repository:**
https://data.crossda.hr

**Location of the repository (city or street address if possible):**
Faculty of Humanities and Socal Sciences
I. Lučića 3, HR-10000 Zagreb, Croatia
45.79641, 15.97162

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:**
The Croatian Social Science Data Archive (CROSSDA) is a national infrastructure public service whose role is to ensure the long-term preservation and dissemination of social science research data. 

**Email address of repository contact:**
mglavica@ffzg.hr

**Year when repository started operating:**
2020

**DOI authority (if applicable):**
DataCite

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by shlake** [comment]
@jggautier it's been awhile since I've updated this map. Do you need to do anything with the "other" map file. Is there another map file anymore?

**Comment by shlake** [comment]
@jggautier I guess one only needs to update the map with the crowd-sourced spreadsheet. Seems to have worked. CROSSDA now on Dataverse Installations map.

**Comment by shlake** [comment]
@mglavica CROSSDA now on Dataverse Installations map. https://iqss.github.io/dataverse-installations/

**Comment by jggautier** [comment]
Right! @pdurbin moved everything into the crowd-sourced spreadsheet :)

**Comment by mglavica** [comment]
Wow, that was fast :) Thank you @shlake and all!
